// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtime-bidding.proto

package com.example.protobuf.google;

public interface BidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique request id generated by Google. This is 16 bytes long.
   * </pre>
   *
   * <code>required bytes id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * Unique request id generated by Google. This is 16 bytes long.
   * </pre>
   *
   * <code>required bytes id = 2;</code>
   * @return The id.
   */
  com.google.protobuf.ByteString getId();

  /**
   * <pre>
   * The first 3 bytes of the IP address in network byte order for IPv4, or the
   * first 6 bytes for IPv6. Note that the number and position of the bytes
   * included from IPv6 addresses may change later.
   * </pre>
   *
   * <code>optional bytes ip = 4;</code>
   * @return Whether the ip field is set.
   */
  boolean hasIp();
  /**
   * <pre>
   * The first 3 bytes of the IP address in network byte order for IPv4, or the
   * first 6 bytes for IPv6. Note that the number and position of the bytes
   * included from IPv6 addresses may change later.
   * </pre>
   *
   * <code>optional bytes ip = 4;</code>
   * @return The ip.
   */
  com.google.protobuf.ByteString getIp();

  /**
   * <pre>
   * When user_data_treatment is set, the user's cookie/id data is cleared from
   * the request and is not sent in callout.
   * The impacted fields are:
   *  * google_user_id
   *  * hosted_match_data
   *  * mobile.encrypted_advertising_id
   *  * mobile.encrypted_hashed_idfa
   *  * session_id
   * </pre>
   *
   * <code>repeated .BidRequest.UserDataTreatment user_data_treatment = 49;</code>
   * @return A list containing the userDataTreatment.
   */
  java.util.List<com.example.protobuf.google.BidRequest.UserDataTreatment> getUserDataTreatmentList();
  /**
   * <pre>
   * When user_data_treatment is set, the user's cookie/id data is cleared from
   * the request and is not sent in callout.
   * The impacted fields are:
   *  * google_user_id
   *  * hosted_match_data
   *  * mobile.encrypted_advertising_id
   *  * mobile.encrypted_hashed_idfa
   *  * session_id
   * </pre>
   *
   * <code>repeated .BidRequest.UserDataTreatment user_data_treatment = 49;</code>
   * @return The count of userDataTreatment.
   */
  int getUserDataTreatmentCount();
  /**
   * <pre>
   * When user_data_treatment is set, the user's cookie/id data is cleared from
   * the request and is not sent in callout.
   * The impacted fields are:
   *  * google_user_id
   *  * hosted_match_data
   *  * mobile.encrypted_advertising_id
   *  * mobile.encrypted_hashed_idfa
   *  * session_id
   * </pre>
   *
   * <code>repeated .BidRequest.UserDataTreatment user_data_treatment = 49;</code>
   * @param index The index of the element to return.
   * @return The userDataTreatment at the given index.
   */
  com.example.protobuf.google.BidRequest.UserDataTreatment getUserDataTreatment(int index);

  /**
   * <pre>
   * The Google ID for the user. This field is the unpadded web-safe base64
   * encoded version of a binary cookie id. See the "Base 64 Encoding with URL
   * and Filename Safe Alphabet" section in RFC 3548 for encoding details. This
   * field may be the same as the Google ID returned by the cookie matching
   * service. Not set if there is one or more user_data_treatment value.
   * </pre>
   *
   * <code>optional string google_user_id = 21;</code>
   * @return Whether the googleUserId field is set.
   */
  boolean hasGoogleUserId();
  /**
   * <pre>
   * The Google ID for the user. This field is the unpadded web-safe base64
   * encoded version of a binary cookie id. See the "Base 64 Encoding with URL
   * and Filename Safe Alphabet" section in RFC 3548 for encoding details. This
   * field may be the same as the Google ID returned by the cookie matching
   * service. Not set if there is one or more user_data_treatment value.
   * </pre>
   *
   * <code>optional string google_user_id = 21;</code>
   * @return The googleUserId.
   */
  java.lang.String getGoogleUserId();
  /**
   * <pre>
   * The Google ID for the user. This field is the unpadded web-safe base64
   * encoded version of a binary cookie id. See the "Base 64 Encoding with URL
   * and Filename Safe Alphabet" section in RFC 3548 for encoding details. This
   * field may be the same as the Google ID returned by the cookie matching
   * service. Not set if there is one or more user_data_treatment value.
   * </pre>
   *
   * <code>optional string google_user_id = 21;</code>
   * @return The bytes for googleUserId.
   */
  com.google.protobuf.ByteString
      getGoogleUserIdBytes();

  /**
   * <pre>
   * The version number of the google_user_id. We may sometimes change the
   * mapping from cookie to google_user_id. In this case the version will be
   * incremented.
   * </pre>
   *
   * <code>optional uint32 cookie_version = 20;</code>
   * @return Whether the cookieVersion field is set.
   */
  boolean hasCookieVersion();
  /**
   * <pre>
   * The version number of the google_user_id. We may sometimes change the
   * mapping from cookie to google_user_id. In this case the version will be
   * incremented.
   * </pre>
   *
   * <code>optional uint32 cookie_version = 20;</code>
   * @return The cookieVersion.
   */
  int getCookieVersion();

  /**
   * <pre>
   * The time in seconds since the google_user_id was created.
   * This number may be quantized.
   * </pre>
   *
   * <code>optional int32 cookie_age_seconds = 31;</code>
   * @return Whether the cookieAgeSeconds field is set.
   */
  boolean hasCookieAgeSeconds();
  /**
   * <pre>
   * The time in seconds since the google_user_id was created.
   * This number may be quantized.
   * </pre>
   *
   * <code>optional int32 cookie_age_seconds = 31;</code>
   * @return The cookieAgeSeconds.
   */
  int getCookieAgeSeconds();

  /**
   * <pre>
   * Match data stored for this google_user_id through the cookie matching
   * service. If a match exists, then this field holds the decoded data that
   * was passed in the google_hm parameter.
   * Not set if there is one or more user_data_treatment value.
   * </pre>
   *
   * <code>optional bytes hosted_match_data = 37;</code>
   * @return Whether the hostedMatchData field is set.
   */
  boolean hasHostedMatchData();
  /**
   * <pre>
   * Match data stored for this google_user_id through the cookie matching
   * service. If a match exists, then this field holds the decoded data that
   * was passed in the google_hm parameter.
   * Not set if there is one or more user_data_treatment value.
   * </pre>
   *
   * <code>optional bytes hosted_match_data = 37;</code>
   * @return The hostedMatchData.
   */
  com.google.protobuf.ByteString getHostedMatchData();

  /**
   * <pre>
   * Represents a short-lived user session on CTV/OTT devices,
   * with a maximum session duration of 6 hours.
   * The use of session_id is never allowed for ads personalization.
   * session_id may only be used for frequency capping, competitive exclusions
   * or related purposes.
   * </pre>
   *
   * <code>optional string session_id = 65;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <pre>
   * Represents a short-lived user session on CTV/OTT devices,
   * with a maximum session duration of 6 hours.
   * The use of session_id is never allowed for ads personalization.
   * session_id may only be used for frequency capping, competitive exclusions
   * or related purposes.
   * </pre>
   *
   * <code>optional string session_id = 65;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * Represents a short-lived user session on CTV/OTT devices,
   * with a maximum session duration of 6 hours.
   * The use of session_id is never allowed for ads personalization.
   * session_id may only be used for frequency capping, competitive exclusions
   * or related purposes.
   * </pre>
   *
   * <code>optional string session_id = 65;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * A string that identifies the browser and type of device that sent the
   * request. Certain data may be redacted or replaced.
   * </pre>
   *
   * <code>optional string user_agent = 6;</code>
   * @return Whether the userAgent field is set.
   */
  boolean hasUserAgent();
  /**
   * <pre>
   * A string that identifies the browser and type of device that sent the
   * request. Certain data may be redacted or replaced.
   * </pre>
   *
   * <code>optional string user_agent = 6;</code>
   * @return The userAgent.
   */
  java.lang.String getUserAgent();
  /**
   * <pre>
   * A string that identifies the browser and type of device that sent the
   * request. Certain data may be redacted or replaced.
   * </pre>
   *
   * <code>optional string user_agent = 6;</code>
   * @return The bytes for userAgent.
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  /**
   * <code>optional .BidRequest.PrivacyTreatments privacy_treatments = 71;</code>
   * @return Whether the privacyTreatments field is set.
   */
  boolean hasPrivacyTreatments();
  /**
   * <code>optional .BidRequest.PrivacyTreatments privacy_treatments = 71;</code>
   * @return The privacyTreatments.
   */
  com.example.protobuf.google.BidRequest.PrivacyTreatments getPrivacyTreatments();
  /**
   * <code>optional .BidRequest.PrivacyTreatments privacy_treatments = 71;</code>
   */
  com.example.protobuf.google.BidRequest.PrivacyTreatmentsOrBuilder getPrivacyTreatmentsOrBuilder();

  /**
   * <pre>
   * User Agent information.
   * </pre>
   *
   * <code>optional .BidRequest.UserAgent user_agent_data = 63;</code>
   * @return Whether the userAgentData field is set.
   */
  boolean hasUserAgentData();
  /**
   * <pre>
   * User Agent information.
   * </pre>
   *
   * <code>optional .BidRequest.UserAgent user_agent_data = 63;</code>
   * @return The userAgentData.
   */
  com.example.protobuf.google.BidRequest.UserAgent getUserAgentData();
  /**
   * <pre>
   * User Agent information.
   * </pre>
   *
   * <code>optional .BidRequest.UserAgent user_agent_data = 63;</code>
   */
  com.example.protobuf.google.BidRequest.UserAgentOrBuilder getUserAgentDataOrBuilder();

  /**
   * <pre>
   * The billing address country of the publisher. This may be different from
   * the detected country of the user in geo_criteria_id or the hosting country
   * of the website. For a complete list of country codes, please refer to
   * https://developers.google.com/google-ads/api/reference/data/codes-formats#country_codes
   * </pre>
   *
   * <code>optional string publisher_country = 55;</code>
   * @return Whether the publisherCountry field is set.
   */
  boolean hasPublisherCountry();
  /**
   * <pre>
   * The billing address country of the publisher. This may be different from
   * the detected country of the user in geo_criteria_id or the hosting country
   * of the website. For a complete list of country codes, please refer to
   * https://developers.google.com/google-ads/api/reference/data/codes-formats#country_codes
   * </pre>
   *
   * <code>optional string publisher_country = 55;</code>
   * @return The publisherCountry.
   */
  java.lang.String getPublisherCountry();
  /**
   * <pre>
   * The billing address country of the publisher. This may be different from
   * the detected country of the user in geo_criteria_id or the hosting country
   * of the website. For a complete list of country codes, please refer to
   * https://developers.google.com/google-ads/api/reference/data/codes-formats#country_codes
   * </pre>
   *
   * <code>optional string publisher_country = 55;</code>
   * @return The bytes for publisherCountry.
   */
  com.google.protobuf.ByteString
      getPublisherCountryBytes();

  /**
   * <pre>
   * The ID of the host publisher. When populated, indicates that the host
   * publisher participated in revenue sharing, and the ID can be used to
   * authorize ads.txt.
   * </pre>
   *
   * <code>optional string host_publisher_id = 73;</code>
   * @return Whether the hostPublisherId field is set.
   */
  boolean hasHostPublisherId();
  /**
   * <pre>
   * The ID of the host publisher. When populated, indicates that the host
   * publisher participated in revenue sharing, and the ID can be used to
   * authorize ads.txt.
   * </pre>
   *
   * <code>optional string host_publisher_id = 73;</code>
   * @return The hostPublisherId.
   */
  java.lang.String getHostPublisherId();
  /**
   * <pre>
   * The ID of the host publisher. When populated, indicates that the host
   * publisher participated in revenue sharing, and the ID can be used to
   * authorize ads.txt.
   * </pre>
   *
   * <code>optional string host_publisher_id = 73;</code>
   * @return The bytes for hostPublisherId.
   */
  com.google.protobuf.ByteString
      getHostPublisherIdBytes();

  /**
   * <pre>
   * Location of the end user. Uses a subset of the codes used in the Google
   * Ads API. See the geo-table.csv table in the technical documentation for a
   * list of IDs. The geo_criteria_id field replaces the deprecated country,
   * region, city, and metro fields.
   * It is recommended that BidRequest.geo be used instead of this field.
   * See Geotargeting Guide:
   * https://developers.google.com/authorized-buyers/rtb/geotargeting
   * </pre>
   *
   * <code>optional int32 geo_criteria_id = 39;</code>
   * @return Whether the geoCriteriaId field is set.
   */
  boolean hasGeoCriteriaId();
  /**
   * <pre>
   * Location of the end user. Uses a subset of the codes used in the Google
   * Ads API. See the geo-table.csv table in the technical documentation for a
   * list of IDs. The geo_criteria_id field replaces the deprecated country,
   * region, city, and metro fields.
   * It is recommended that BidRequest.geo be used instead of this field.
   * See Geotargeting Guide:
   * https://developers.google.com/authorized-buyers/rtb/geotargeting
   * </pre>
   *
   * <code>optional int32 geo_criteria_id = 39;</code>
   * @return The geoCriteriaId.
   */
  int getGeoCriteriaId();

  /**
   * <code>optional .BidRequest.Geo geo = 62;</code>
   * @return Whether the geo field is set.
   */
  boolean hasGeo();
  /**
   * <code>optional .BidRequest.Geo geo = 62;</code>
   * @return The geo.
   */
  com.example.protobuf.google.BidRequest.Geo getGeo();
  /**
   * <code>optional .BidRequest.Geo geo = 62;</code>
   */
  com.example.protobuf.google.BidRequest.GeoOrBuilder getGeoOrBuilder();

  /**
   * <pre>
   * Detected postal code of the appropriate type for the country of the end
   * user (e.g., zip code if the country is "US"). The postal_code_prefix field
   * is set when accuracy is too low to imply a full code, otherwise the
   * postal_code field is set.
   * It is recommended that BidRequest.geo be used instead of this field.
   * See Geotargeting Guide:
   * https://developers.google.com/authorized-buyers/rtb/geotargeting
   * </pre>
   *
   * <code>optional string postal_code = 33;</code>
   * @return Whether the postalCode field is set.
   */
  boolean hasPostalCode();
  /**
   * <pre>
   * Detected postal code of the appropriate type for the country of the end
   * user (e.g., zip code if the country is "US"). The postal_code_prefix field
   * is set when accuracy is too low to imply a full code, otherwise the
   * postal_code field is set.
   * It is recommended that BidRequest.geo be used instead of this field.
   * See Geotargeting Guide:
   * https://developers.google.com/authorized-buyers/rtb/geotargeting
   * </pre>
   *
   * <code>optional string postal_code = 33;</code>
   * @return The postalCode.
   */
  java.lang.String getPostalCode();
  /**
   * <pre>
   * Detected postal code of the appropriate type for the country of the end
   * user (e.g., zip code if the country is "US"). The postal_code_prefix field
   * is set when accuracy is too low to imply a full code, otherwise the
   * postal_code field is set.
   * It is recommended that BidRequest.geo be used instead of this field.
   * See Geotargeting Guide:
   * https://developers.google.com/authorized-buyers/rtb/geotargeting
   * </pre>
   *
   * <code>optional string postal_code = 33;</code>
   * @return The bytes for postalCode.
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  /**
   * <pre>
   * It is recommended that BidRequest.geo be used instead of this field.
   * See Geotargeting Guide:
   * https://developers.google.com/authorized-buyers/rtb/geotargeting
   * </pre>
   *
   * <code>optional string postal_code_prefix = 34;</code>
   * @return Whether the postalCodePrefix field is set.
   */
  boolean hasPostalCodePrefix();
  /**
   * <pre>
   * It is recommended that BidRequest.geo be used instead of this field.
   * See Geotargeting Guide:
   * https://developers.google.com/authorized-buyers/rtb/geotargeting
   * </pre>
   *
   * <code>optional string postal_code_prefix = 34;</code>
   * @return The postalCodePrefix.
   */
  java.lang.String getPostalCodePrefix();
  /**
   * <pre>
   * It is recommended that BidRequest.geo be used instead of this field.
   * See Geotargeting Guide:
   * https://developers.google.com/authorized-buyers/rtb/geotargeting
   * </pre>
   *
   * <code>optional string postal_code_prefix = 34;</code>
   * @return The bytes for postalCodePrefix.
   */
  com.google.protobuf.ByteString
      getPostalCodePrefixBytes();

  /**
   * <pre>
   * Hyperlocal targeting signal when available, encrypted as described at
   * https://developers.google.com/authorized-buyers/rtb/response-guide/decrypt-hyperlocal
   * </pre>
   *
   * <code>optional bytes encrypted_hyperlocal_set = 40;</code>
   * @return Whether the encryptedHyperlocalSet field is set.
   */
  boolean hasEncryptedHyperlocalSet();
  /**
   * <pre>
   * Hyperlocal targeting signal when available, encrypted as described at
   * https://developers.google.com/authorized-buyers/rtb/response-guide/decrypt-hyperlocal
   * </pre>
   *
   * <code>optional bytes encrypted_hyperlocal_set = 40;</code>
   * @return The encryptedHyperlocalSet.
   */
  com.google.protobuf.ByteString getEncryptedHyperlocalSet();

  /**
   * <pre>
   * Unencrypted version of encrypted_hyperlocal_set. This field is only set
   * when using an SSL connection.
   * </pre>
   *
   * <code>optional .BidRequest.HyperlocalSet hyperlocal_set = 53;</code>
   * @return Whether the hyperlocalSet field is set.
   */
  boolean hasHyperlocalSet();
  /**
   * <pre>
   * Unencrypted version of encrypted_hyperlocal_set. This field is only set
   * when using an SSL connection.
   * </pre>
   *
   * <code>optional .BidRequest.HyperlocalSet hyperlocal_set = 53;</code>
   * @return The hyperlocalSet.
   */
  com.example.protobuf.google.BidRequest.HyperlocalSet getHyperlocalSet();
  /**
   * <pre>
   * Unencrypted version of encrypted_hyperlocal_set. This field is only set
   * when using an SSL connection.
   * </pre>
   *
   * <code>optional .BidRequest.HyperlocalSet hyperlocal_set = 53;</code>
   */
  com.example.protobuf.google.BidRequest.HyperlocalSetOrBuilder getHyperlocalSetOrBuilder();

  /**
   * <pre>
   * The offset of the user's time from GMT in minutes. For example, GMT+10 is
   * timezone_offset = 600.
   * </pre>
   *
   * <code>optional int32 timezone_offset = 25;</code>
   * @return Whether the timezoneOffset field is set.
   */
  boolean hasTimezoneOffset();
  /**
   * <pre>
   * The offset of the user's time from GMT in minutes. For example, GMT+10 is
   * timezone_offset = 600.
   * </pre>
   *
   * <code>optional int32 timezone_offset = 25;</code>
   * @return The timezoneOffset.
   */
  int getTimezoneOffset();

  /**
   * <code>repeated .BidRequest.UserList user_list = 32;</code>
   */
  java.util.List<com.example.protobuf.google.BidRequest.UserList> 
      getUserListList();
  /**
   * <code>repeated .BidRequest.UserList user_list = 32;</code>
   */
  com.example.protobuf.google.BidRequest.UserList getUserList(int index);
  /**
   * <code>repeated .BidRequest.UserList user_list = 32;</code>
   */
  int getUserListCount();
  /**
   * <code>repeated .BidRequest.UserList user_list = 32;</code>
   */
  java.util.List<? extends com.example.protobuf.google.BidRequest.UserListOrBuilder> 
      getUserListOrBuilderList();
  /**
   * <code>repeated .BidRequest.UserList user_list = 32;</code>
   */
  com.example.protobuf.google.BidRequest.UserListOrBuilder getUserListOrBuilder(
      int index);

  /**
   * <pre>
   * The publisher ID as defined by the publisher code suffix of
   * the web property code. For instance, "pub-123" is the publisher code of web
   * property code "ca-pub-123" (ca- is the product specific prefix of the web
   * property).
   * </pre>
   *
   * <code>optional string publisher_id = 56;</code>
   * @return Whether the publisherId field is set.
   */
  boolean hasPublisherId();
  /**
   * <pre>
   * The publisher ID as defined by the publisher code suffix of
   * the web property code. For instance, "pub-123" is the publisher code of web
   * property code "ca-pub-123" (ca- is the product specific prefix of the web
   * property).
   * </pre>
   *
   * <code>optional string publisher_id = 56;</code>
   * @return The publisherId.
   */
  java.lang.String getPublisherId();
  /**
   * <pre>
   * The publisher ID as defined by the publisher code suffix of
   * the web property code. For instance, "pub-123" is the publisher code of web
   * property code "ca-pub-123" (ca- is the product specific prefix of the web
   * property).
   * </pre>
   *
   * <code>optional string publisher_id = 56;</code>
   * @return The bytes for publisherId.
   */
  com.google.protobuf.ByteString
      getPublisherIdBytes();

  /**
   * <pre>
   * The seller network id. See seller-network-ids.txt file in the technical
   * documentation for a list of ids. This is only set if the site is not
   * anonymous and the publisher allows site targeting.
   * </pre>
   *
   * <code>optional int32 seller_network_id = 41;</code>
   * @return Whether the sellerNetworkId field is set.
   */
  boolean hasSellerNetworkId();
  /**
   * <pre>
   * The seller network id. See seller-network-ids.txt file in the technical
   * documentation for a list of ids. This is only set if the site is not
   * anonymous and the publisher allows site targeting.
   * </pre>
   *
   * <code>optional int32 seller_network_id = 41;</code>
   * @return The sellerNetworkId.
   */
  int getSellerNetworkId();

  /**
   * <pre>
   * Id for the partner that provides this inventory. This is only set when
   * seller_network_id is also set and further partner information beyond the
   * seller_network_id is also available. The value of the partner_id is not
   * meaningful beyond providing a stable identifier.
   * </pre>
   *
   * <code>optional fixed64 partner_id = 52;</code>
   * @return Whether the partnerId field is set.
   */
  boolean hasPartnerId();
  /**
   * <pre>
   * Id for the partner that provides this inventory. This is only set when
   * seller_network_id is also set and further partner information beyond the
   * seller_network_id is also available. The value of the partner_id is not
   * meaningful beyond providing a stable identifier.
   * </pre>
   *
   * <code>optional fixed64 partner_id = 52;</code>
   * @return The partnerId.
   */
  long getPartnerId();

  /**
   * <pre>
   * The URL of the page with parameters removed. This is only set if the
   * publisher allows site targeting. This always starts with a protocol (either
   * http or https).
   * </pre>
   *
   * <code>optional string url = 11;</code>
   * @return Whether the url field is set.
   */
  boolean hasUrl();
  /**
   * <pre>
   * The URL of the page with parameters removed. This is only set if the
   * publisher allows site targeting. This always starts with a protocol (either
   * http or https).
   * </pre>
   *
   * <code>optional string url = 11;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * The URL of the page with parameters removed. This is only set if the
   * publisher allows site targeting. This always starts with a protocol (either
   * http or https).
   * </pre>
   *
   * <code>optional string url = 11;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * Indicates that the request is using semi-transparent branding,
   * which means only a truncated version of the request URL will
   * be provided. This decision is made by the publisher, see
   * https://support.google.com/admanager/answer/4584891#urls for context.
   * </pre>
   *
   * <code>optional bool is_semi_transparent_request = 67;</code>
   * @return Whether the isSemiTransparentRequest field is set.
   */
  boolean hasIsSemiTransparentRequest();
  /**
   * <pre>
   * Indicates that the request is using semi-transparent branding,
   * which means only a truncated version of the request URL will
   * be provided. This decision is made by the publisher, see
   * https://support.google.com/admanager/answer/4584891#urls for context.
   * </pre>
   *
   * <code>optional bool is_semi_transparent_request = 67;</code>
   * @return The isSemiTransparentRequest.
   */
  boolean getIsSemiTransparentRequest();

  /**
   * <pre>
   * Detected user languages, based on the language of the web page, the browser
   * settings, and other signals. The order is arbitrary. The codes are 2 or 5
   * characters and are documented at
   * https://developers.google.com/google-ads/api/reference/data/codes-formats#languages
   * </pre>
   *
   * <code>repeated string detected_language = 12;</code>
   * @return A list containing the detectedLanguage.
   */
  java.util.List<java.lang.String>
      getDetectedLanguageList();
  /**
   * <pre>
   * Detected user languages, based on the language of the web page, the browser
   * settings, and other signals. The order is arbitrary. The codes are 2 or 5
   * characters and are documented at
   * https://developers.google.com/google-ads/api/reference/data/codes-formats#languages
   * </pre>
   *
   * <code>repeated string detected_language = 12;</code>
   * @return The count of detectedLanguage.
   */
  int getDetectedLanguageCount();
  /**
   * <pre>
   * Detected user languages, based on the language of the web page, the browser
   * settings, and other signals. The order is arbitrary. The codes are 2 or 5
   * characters and are documented at
   * https://developers.google.com/google-ads/api/reference/data/codes-formats#languages
   * </pre>
   *
   * <code>repeated string detected_language = 12;</code>
   * @param index The index of the element to return.
   * @return The detectedLanguage at the given index.
   */
  java.lang.String getDetectedLanguage(int index);
  /**
   * <pre>
   * Detected user languages, based on the language of the web page, the browser
   * settings, and other signals. The order is arbitrary. The codes are 2 or 5
   * characters and are documented at
   * https://developers.google.com/google-ads/api/reference/data/codes-formats#languages
   * </pre>
   *
   * <code>repeated string detected_language = 12;</code>
   * @param index The index of the value to return.
   * @return The bytes of the detectedLanguage at the given index.
   */
  com.google.protobuf.ByteString
      getDetectedLanguageBytes(int index);

  /**
   * <pre>
   * Unordered list of detected content verticals. See the
   * publisher-verticals.txt file in the technical documentation for a list of
   * ids.
   * </pre>
   *
   * <code>repeated .BidRequest.Vertical detected_vertical = 13;</code>
   */
  java.util.List<com.example.protobuf.google.BidRequest.Vertical> 
      getDetectedVerticalList();
  /**
   * <pre>
   * Unordered list of detected content verticals. See the
   * publisher-verticals.txt file in the technical documentation for a list of
   * ids.
   * </pre>
   *
   * <code>repeated .BidRequest.Vertical detected_vertical = 13;</code>
   */
  com.example.protobuf.google.BidRequest.Vertical getDetectedVertical(int index);
  /**
   * <pre>
   * Unordered list of detected content verticals. See the
   * publisher-verticals.txt file in the technical documentation for a list of
   * ids.
   * </pre>
   *
   * <code>repeated .BidRequest.Vertical detected_vertical = 13;</code>
   */
  int getDetectedVerticalCount();
  /**
   * <pre>
   * Unordered list of detected content verticals. See the
   * publisher-verticals.txt file in the technical documentation for a list of
   * ids.
   * </pre>
   *
   * <code>repeated .BidRequest.Vertical detected_vertical = 13;</code>
   */
  java.util.List<? extends com.example.protobuf.google.BidRequest.VerticalOrBuilder> 
      getDetectedVerticalOrBuilderList();
  /**
   * <pre>
   * Unordered list of detected content verticals. See the
   * publisher-verticals.txt file in the technical documentation for a list of
   * ids.
   * </pre>
   *
   * <code>repeated .BidRequest.Vertical detected_vertical = 13;</code>
   */
  com.example.protobuf.google.BidRequest.VerticalOrBuilder getDetectedVerticalOrBuilder(
      int index);

  /**
   * <pre>
   * List of detected content labels. See content-labels.txt file in the
   * technical documentation for a list of ids.
   * </pre>
   *
   * <code>repeated int32 detected_content_label = 26 [packed = true];</code>
   * @return A list containing the detectedContentLabel.
   */
  java.util.List<java.lang.Integer> getDetectedContentLabelList();
  /**
   * <pre>
   * List of detected content labels. See content-labels.txt file in the
   * technical documentation for a list of ids.
   * </pre>
   *
   * <code>repeated int32 detected_content_label = 26 [packed = true];</code>
   * @return The count of detectedContentLabel.
   */
  int getDetectedContentLabelCount();
  /**
   * <pre>
   * List of detected content labels. See content-labels.txt file in the
   * technical documentation for a list of ids.
   * </pre>
   *
   * <code>repeated int32 detected_content_label = 26 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The detectedContentLabel at the given index.
   */
  int getDetectedContentLabel(int index);

  /**
   * <pre>
   * This represents a unique ID for the overall query. In the event
   * that there are multiple callouts for a query, all callout requests for that
   * query will contain the same google_query_id.
   * </pre>
   *
   * <code>optional string google_query_id = 59;</code>
   * @return Whether the googleQueryId field is set.
   */
  boolean hasGoogleQueryId();
  /**
   * <pre>
   * This represents a unique ID for the overall query. In the event
   * that there are multiple callouts for a query, all callout requests for that
   * query will contain the same google_query_id.
   * </pre>
   *
   * <code>optional string google_query_id = 59;</code>
   * @return The googleQueryId.
   */
  java.lang.String getGoogleQueryId();
  /**
   * <pre>
   * This represents a unique ID for the overall query. In the event
   * that there are multiple callouts for a query, all callout requests for that
   * query will contain the same google_query_id.
   * </pre>
   *
   * <code>optional string google_query_id = 59;</code>
   * @return The bytes for googleQueryId.
   */
  com.google.protobuf.ByteString
      getGoogleQueryIdBytes();

  /**
   * <code>optional .BidRequest.AuctionType auction_type = 60 [default = SECOND_PRICE];</code>
   * @return Whether the auctionType field is set.
   */
  boolean hasAuctionType();
  /**
   * <code>optional .BidRequest.AuctionType auction_type = 60 [default = SECOND_PRICE];</code>
   * @return The auctionType.
   */
  com.example.protobuf.google.BidRequest.AuctionType getAuctionType();

  /**
   * <code>optional .BidRequest.Device device = 54;</code>
   * @return Whether the device field is set.
   */
  boolean hasDevice();
  /**
   * <code>optional .BidRequest.Device device = 54;</code>
   * @return The device.
   */
  com.example.protobuf.google.BidRequest.Device getDevice();
  /**
   * <code>optional .BidRequest.Device device = 54;</code>
   */
  com.example.protobuf.google.BidRequest.DeviceOrBuilder getDeviceOrBuilder();

  /**
   * <code>repeated .BidRequest.KeyValue key_value = 38;</code>
   */
  java.util.List<com.example.protobuf.google.BidRequest.KeyValue> 
      getKeyValueList();
  /**
   * <code>repeated .BidRequest.KeyValue key_value = 38;</code>
   */
  com.example.protobuf.google.BidRequest.KeyValue getKeyValue(int index);
  /**
   * <code>repeated .BidRequest.KeyValue key_value = 38;</code>
   */
  int getKeyValueCount();
  /**
   * <code>repeated .BidRequest.KeyValue key_value = 38;</code>
   */
  java.util.List<? extends com.example.protobuf.google.BidRequest.KeyValueOrBuilder> 
      getKeyValueOrBuilderList();
  /**
   * <code>repeated .BidRequest.KeyValue key_value = 38;</code>
   */
  com.example.protobuf.google.BidRequest.KeyValueOrBuilder getKeyValueOrBuilder(
      int index);

  /**
   * <code>optional .BidRequest.Mobile mobile = 28;</code>
   * @return Whether the mobile field is set.
   */
  boolean hasMobile();
  /**
   * <code>optional .BidRequest.Mobile mobile = 28;</code>
   * @return The mobile.
   */
  com.example.protobuf.google.BidRequest.Mobile getMobile();
  /**
   * <code>optional .BidRequest.Mobile mobile = 28;</code>
   */
  com.example.protobuf.google.BidRequest.MobileOrBuilder getMobileOrBuilder();

  /**
   * <code>optional .BidRequest.Video video = 29;</code>
   * @return Whether the video field is set.
   */
  boolean hasVideo();
  /**
   * <code>optional .BidRequest.Video video = 29;</code>
   * @return The video.
   */
  com.example.protobuf.google.BidRequest.Video getVideo();
  /**
   * <code>optional .BidRequest.Video video = 29;</code>
   */
  com.example.protobuf.google.BidRequest.VideoOrBuilder getVideoOrBuilder();

  /**
   * <pre>
   * The publisher settings list id that applies to this page.
   * See the RTB Publisher Settings guide at
   * https://developers.google.com/authorized-buyers/rtb/pub-settings-guide
   * for details.
   * </pre>
   *
   * <code>optional fixed64 publisher_settings_list_id = 42;</code>
   * @return Whether the publisherSettingsListId field is set.
   */
  boolean hasPublisherSettingsListId();
  /**
   * <pre>
   * The publisher settings list id that applies to this page.
   * See the RTB Publisher Settings guide at
   * https://developers.google.com/authorized-buyers/rtb/pub-settings-guide
   * for details.
   * </pre>
   *
   * <code>optional fixed64 publisher_settings_list_id = 42;</code>
   * @return The publisherSettingsListId.
   */
  long getPublisherSettingsListId();

  /**
   * <code>optional .BidRequest.PublisherType publisher_type = 51 [default = UNKNOWN_PUBLISHER_TYPE];</code>
   * @return Whether the publisherType field is set.
   */
  boolean hasPublisherType();
  /**
   * <code>optional .BidRequest.PublisherType publisher_type = 51 [default = UNKNOWN_PUBLISHER_TYPE];</code>
   * @return The publisherType.
   */
  com.example.protobuf.google.BidRequest.PublisherType getPublisherType();

  /**
   * <pre>
   * The visibility state of the web page containing the ad slots.
   * See https://www.w3.org/TR/page-visibility/.
   * </pre>
   *
   * <code>optional .BidRequest.VisibilityState page_visibility = 66 [default = VISIBILITY_STATE_UNKNOWN];</code>
   * @return Whether the pageVisibility field is set.
   */
  boolean hasPageVisibility();
  /**
   * <pre>
   * The visibility state of the web page containing the ad slots.
   * See https://www.w3.org/TR/page-visibility/.
   * </pre>
   *
   * <code>optional .BidRequest.VisibilityState page_visibility = 66 [default = VISIBILITY_STATE_UNKNOWN];</code>
   * @return The pageVisibility.
   */
  com.example.protobuf.google.BidRequest.VisibilityState getPageVisibility();

  /**
   * <code>repeated .BidRequest.AdSlot adslot = 14;</code>
   */
  java.util.List<com.example.protobuf.google.BidRequest.AdSlot> 
      getAdslotList();
  /**
   * <code>repeated .BidRequest.AdSlot adslot = 14;</code>
   */
  com.example.protobuf.google.BidRequest.AdSlot getAdslot(int index);
  /**
   * <code>repeated .BidRequest.AdSlot adslot = 14;</code>
   */
  int getAdslotCount();
  /**
   * <code>repeated .BidRequest.AdSlot adslot = 14;</code>
   */
  java.util.List<? extends com.example.protobuf.google.BidRequest.AdSlotOrBuilder> 
      getAdslotOrBuilderList();
  /**
   * <code>repeated .BidRequest.AdSlot adslot = 14;</code>
   */
  com.example.protobuf.google.BidRequest.AdSlotOrBuilder getAdslotOrBuilder(
      int index);

  /**
   * <code>repeated .BidRequest.BidResponseFeedback bid_response_feedback = 44;</code>
   */
  java.util.List<com.example.protobuf.google.BidRequest.BidResponseFeedback> 
      getBidResponseFeedbackList();
  /**
   * <code>repeated .BidRequest.BidResponseFeedback bid_response_feedback = 44;</code>
   */
  com.example.protobuf.google.BidRequest.BidResponseFeedback getBidResponseFeedback(int index);
  /**
   * <code>repeated .BidRequest.BidResponseFeedback bid_response_feedback = 44;</code>
   */
  int getBidResponseFeedbackCount();
  /**
   * <code>repeated .BidRequest.BidResponseFeedback bid_response_feedback = 44;</code>
   */
  java.util.List<? extends com.example.protobuf.google.BidRequest.BidResponseFeedbackOrBuilder> 
      getBidResponseFeedbackOrBuilderList();
  /**
   * <code>repeated .BidRequest.BidResponseFeedback bid_response_feedback = 44;</code>
   */
  com.example.protobuf.google.BidRequest.BidResponseFeedbackOrBuilder getBidResponseFeedbackOrBuilder(
      int index);

  /**
   * <pre>
   * How many milliseconds Google will wait for a response before ignoring it.
   * </pre>
   *
   * <code>optional int32 response_deadline_ms = 57;</code>
   * @return Whether the responseDeadlineMs field is set.
   */
  boolean hasResponseDeadlineMs();
  /**
   * <pre>
   * How many milliseconds Google will wait for a response before ignoring it.
   * </pre>
   *
   * <code>optional int32 response_deadline_ms = 57;</code>
   * @return The responseDeadlineMs.
   */
  int getResponseDeadlineMs();

  /**
   * <pre>
   * If true, then this is a test request. Results will not be displayed to
   * users and you will not be billed for a response even if it wins the
   * auction. You should still do regular processing since the request may be
   * used to evaluate latencies or for other testing. During your initial
   * testing with Google traffic any response that you make will be filtered
   * out of the auction whether this flag has a value of true or false.
   * </pre>
   *
   * <code>optional bool is_test = 15 [default = false];</code>
   * @return Whether the isTest field is set.
   */
  boolean hasIsTest();
  /**
   * <pre>
   * If true, then this is a test request. Results will not be displayed to
   * users and you will not be billed for a response even if it wins the
   * auction. You should still do regular processing since the request may be
   * used to evaluate latencies or for other testing. During your initial
   * testing with Google traffic any response that you make will be filtered
   * out of the auction whether this flag has a value of true or false.
   * </pre>
   *
   * <code>optional bool is_test = 15 [default = false];</code>
   * @return The isTest.
   */
  boolean getIsTest();

  /**
   * <pre>
   * If true, then this request is intended to measure network latency. Please
   * return an empty BidResponse with only processing_time_ms set as quickly as
   * possible without executing any bidding logic.
   * </pre>
   *
   * <code>optional bool is_ping = 17 [default = false];</code>
   * @return Whether the isPing field is set.
   */
  boolean hasIsPing();
  /**
   * <pre>
   * If true, then this request is intended to measure network latency. Please
   * return an empty BidResponse with only processing_time_ms set as quickly as
   * possible without executing any bidding logic.
   * </pre>
   *
   * <code>optional bool is_ping = 17 [default = false];</code>
   * @return The isPing.
   */
  boolean getIsPing();

  /**
   * <pre>
   * If true, then the callout model predicted that you will not bid
   * on this request. We send a sampled percentage of such requests so that we
   * can automatically update the model when bidding patterns change.
   * </pre>
   *
   * <code>optional bool is_predicted_to_be_ignored = 45 [default = false];</code>
   * @return Whether the isPredictedToBeIgnored field is set.
   */
  boolean hasIsPredictedToBeIgnored();
  /**
   * <pre>
   * If true, then the callout model predicted that you will not bid
   * on this request. We send a sampled percentage of such requests so that we
   * can automatically update the model when bidding patterns change.
   * </pre>
   *
   * <code>optional bool is_predicted_to_be_ignored = 45 [default = false];</code>
   * @return The isPredictedToBeIgnored.
   */
  boolean getIsPredictedToBeIgnored();

  /**
   * <code>optional .BidRequest.SupplyChain supply_chain = 69;</code>
   * @return Whether the supplyChain field is set.
   */
  boolean hasSupplyChain();
  /**
   * <code>optional .BidRequest.SupplyChain supply_chain = 69;</code>
   * @return The supplyChain.
   */
  com.example.protobuf.google.BidRequest.SupplyChain getSupplyChain();
  /**
   * <code>optional .BidRequest.SupplyChain supply_chain = 69;</code>
   */
  com.example.protobuf.google.BidRequest.SupplyChainOrBuilder getSupplyChainOrBuilder();

  /**
   * <code>optional .BidRequest.FrequencyCappingScope frequency_capping_scope = 70;</code>
   * @return Whether the frequencyCappingScope field is set.
   */
  boolean hasFrequencyCappingScope();
  /**
   * <code>optional .BidRequest.FrequencyCappingScope frequency_capping_scope = 70;</code>
   * @return The frequencyCappingScope.
   */
  com.example.protobuf.google.BidRequest.FrequencyCappingScope getFrequencyCappingScope();
}
