// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtime-bidding.proto

package com.example.protobuf.google;

public interface BidResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BidResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .BidResponse.Ad ad = 2;</code>
   */
  java.util.List<com.example.protobuf.google.BidResponse.Ad> 
      getAdList();
  /**
   * <code>repeated .BidResponse.Ad ad = 2;</code>
   */
  com.example.protobuf.google.BidResponse.Ad getAd(int index);
  /**
   * <code>repeated .BidResponse.Ad ad = 2;</code>
   */
  int getAdCount();
  /**
   * <code>repeated .BidResponse.Ad ad = 2;</code>
   */
  java.util.List<? extends com.example.protobuf.google.BidResponse.AdOrBuilder> 
      getAdOrBuilderList();
  /**
   * <code>repeated .BidResponse.Ad ad = 2;</code>
   */
  com.example.protobuf.google.BidResponse.AdOrBuilder getAdOrBuilder(
      int index);

  /**
   * <pre>
   * If is_test was set in the BidRequest, then you may return debug information
   * as plain text in this field. Please do not set this field under normal
   * conditions, or set it to values longer than 100 characters. You should only
   * use this field when asked to do so as part of troubleshooting particular
   * problems.
   * </pre>
   *
   * <code>optional string debug_string = 5;</code>
   * @return Whether the debugString field is set.
   */
  boolean hasDebugString();
  /**
   * <pre>
   * If is_test was set in the BidRequest, then you may return debug information
   * as plain text in this field. Please do not set this field under normal
   * conditions, or set it to values longer than 100 characters. You should only
   * use this field when asked to do so as part of troubleshooting particular
   * problems.
   * </pre>
   *
   * <code>optional string debug_string = 5;</code>
   * @return The debugString.
   */
  java.lang.String getDebugString();
  /**
   * <pre>
   * If is_test was set in the BidRequest, then you may return debug information
   * as plain text in this field. Please do not set this field under normal
   * conditions, or set it to values longer than 100 characters. You should only
   * use this field when asked to do so as part of troubleshooting particular
   * problems.
   * </pre>
   *
   * <code>optional string debug_string = 5;</code>
   * @return The bytes for debugString.
   */
  com.google.protobuf.ByteString
      getDebugStringBytes();

  /**
   * <pre>
   * Please set this to the processing time in milliseconds from when you
   * received the request to when you returned the response.
   * </pre>
   *
   * <code>optional int32 processing_time_ms = 4;</code>
   * @return Whether the processingTimeMs field is set.
   */
  boolean hasProcessingTimeMs();
  /**
   * <pre>
   * Please set this to the processing time in milliseconds from when you
   * received the request to when you returned the response.
   * </pre>
   *
   * <code>optional int32 processing_time_ms = 4;</code>
   * @return The processingTimeMs.
   */
  int getProcessingTimeMs();

  /**
   * <pre>
   * An optional, bidder-specified reason for not submitting a bid. This field
   * is equivalent to BidResponse.nbr in the OpenRTB protocol and uses the same
   * namespace of no-bid reason codes. See
   * https://developers.google.com/authorized-buyers/rtb/downloads/no-bid-reasons.txt
   * for the full set of no-bid reason codes.
   * </pre>
   *
   * <code>optional int32 no_bid_reason = 6;</code>
   * @return Whether the noBidReason field is set.
   */
  boolean hasNoBidReason();
  /**
   * <pre>
   * An optional, bidder-specified reason for not submitting a bid. This field
   * is equivalent to BidResponse.nbr in the OpenRTB protocol and uses the same
   * namespace of no-bid reason codes. See
   * https://developers.google.com/authorized-buyers/rtb/downloads/no-bid-reasons.txt
   * for the full set of no-bid reason codes.
   * </pre>
   *
   * <code>optional int32 no_bid_reason = 6;</code>
   * @return The noBidReason.
   */
  int getNoBidReason();
}
