// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtime-bidding.proto

package com.example.protobuf.google;

public final class RealtimeBidding {
  private RealtimeBidding() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_PrivacyTreatments_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_PrivacyTreatments_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_UserAgent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_UserAgent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_UserAgent_BrandVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_UserAgent_BrandVersion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Geo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Geo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Hyperlocal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Hyperlocal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Hyperlocal_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Hyperlocal_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_HyperlocalSet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_HyperlocalSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_UserList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_UserList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Vertical_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Vertical_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Device_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Device_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Device_OsVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Device_OsVersion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_KeyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Mobile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Mobile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Mobile_InstalledSdk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Mobile_InstalledSdk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Mobile_InstalledSdk_Version_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Mobile_InstalledSdk_Version_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Mobile_SKAdNetworkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Mobile_SKAdNetworkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Video_CompanionSlot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Video_CompanionSlot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_Video_ContentAttributes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_Video_ContentAttributes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_FlexibleAdSlotSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_FlexibleAdSlotSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_ConsentedProvidersSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_ConsentedProvidersSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_ExcludedCreative_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_ExcludedCreative_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_MatchingAdData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_MatchingAdData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_MatchingAdData_DirectDeal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_MatchingAdData_DirectDeal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_ExchangeBidding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_ExchangeBidding_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_OpenBidding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_OpenBidding_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_CreativeEnforcementSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_CreativeEnforcementSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_NativeAdTemplate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_NativeAdTemplate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_AutoRefresh_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_AutoRefresh_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_AutoRefresh_AutoRefreshSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_AutoRefresh_AutoRefreshSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_StickySettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_StickySettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceApp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceApp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceJs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceJs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_AdSlot_MultiAdsCellInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_AdSlot_MultiAdsCellInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_BidResponseFeedback_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_BidResponseFeedback_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_SupplyChain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_SupplyChain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_SupplyChain_SupplyChainNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_SupplyChain_SupplyChainNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_NativeAd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_NativeAd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_NativeAd_Image_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_NativeAd_Image_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_AdSlot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_AdSlot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_AdSlot_FrequencyCap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_AdSlot_FrequencyCap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_ImpressionTrackingResource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_ImpressionTrackingResource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_SdkRenderedAd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_SdkRenderedAd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_SdkRenderedAd_DeclaredAd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_SdkRenderedAd_DeclaredAd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_SKAdNetworkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_SKAdNetworkResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_SKAdNetworkResponse_Fidelity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_SKAdNetworkResponse_Fidelity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidResponse_Ad_SKAdNetworkResponse_SKAdNetworkOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidResponse_Ad_SKAdNetworkResponse_SKAdNetworkOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026realtime-bidding.proto\032\036google/protobu" +
      "f/duration.proto\032\034google/protobuf/struct" +
      ".proto\"\224u\n\nBidRequest\022\n\n\002id\030\002 \002(\014\022\n\n\002ip\030" +
      "\004 \001(\014\022:\n\023user_data_treatment\0301 \003(\0162\035.Bid" +
      "Request.UserDataTreatment\022\026\n\016google_user" +
      "_id\030\025 \001(\t\022\026\n\016cookie_version\030\024 \001(\r\022\032\n\022coo" +
      "kie_age_seconds\030\037 \001(\005\022\031\n\021hosted_match_da" +
      "ta\030% \001(\014\022\022\n\nsession_id\030A \001(\t\022\022\n\nuser_age" +
      "nt\030\006 \001(\t\0229\n\022privacy_treatments\030G \001(\0132\035.B" +
      "idRequest.PrivacyTreatments\022.\n\017user_agen" +
      "t_data\030? \001(\0132\025.BidRequest.UserAgent\022\031\n\021p" +
      "ublisher_country\0307 \001(\t\022\031\n\021host_publisher" +
      "_id\030I \001(\t\022\027\n\017geo_criteria_id\030\' \001(\005\022\034\n\003ge" +
      "o\030> \001(\0132\017.BidRequest.Geo\022\023\n\013postal_code\030" +
      "! \001(\t\022\032\n\022postal_code_prefix\030\" \001(\t\022 \n\030enc" +
      "rypted_hyperlocal_set\030( \001(\014\0221\n\016hyperloca" +
      "l_set\0305 \001(\0132\031.BidRequest.HyperlocalSet\022\027" +
      "\n\017timezone_offset\030\031 \001(\005\022\'\n\tuser_list\030  \003" +
      "(\0132\024.BidRequest.UserList\022\024\n\014publisher_id" +
      "\0308 \001(\t\022\031\n\021seller_network_id\030) \001(\005\022\022\n\npar" +
      "tner_id\0304 \001(\006\022\013\n\003url\030\013 \001(\t\022#\n\033is_semi_tr" +
      "ansparent_request\030C \001(\010\022\031\n\021detected_lang" +
      "uage\030\014 \003(\t\022/\n\021detected_vertical\030\r \003(\0132\024." +
      "BidRequest.Vertical\022\"\n\026detected_content_" +
      "label\030\032 \003(\005B\002\020\001\022\027\n\017google_query_id\030; \001(\t" +
      "\022;\n\014auction_type\030< \001(\0162\027.BidRequest.Auct" +
      "ionType:\014SECOND_PRICE\022\"\n\006device\0306 \001(\0132\022." +
      "BidRequest.Device\022\'\n\tkey_value\030& \003(\0132\024.B" +
      "idRequest.KeyValue\022\"\n\006mobile\030\034 \001(\0132\022.Bid" +
      "Request.Mobile\022 \n\005video\030\035 \001(\0132\021.BidReque" +
      "st.Video\022\"\n\032publisher_settings_list_id\030*" +
      " \001(\006\022I\n\016publisher_type\0303 \001(\0162\031.BidReques" +
      "t.PublisherType:\026UNKNOWN_PUBLISHER_TYPE\022" +
      "N\n\017page_visibility\030B \001(\0162\033.BidRequest.Vi" +
      "sibilityState:\030VISIBILITY_STATE_UNKNOWN\022" +
      "\"\n\006adslot\030\016 \003(\0132\022.BidRequest.AdSlot\022>\n\025b" +
      "id_response_feedback\030, \003(\0132\037.BidRequest." +
      "BidResponseFeedback\022\034\n\024response_deadline" +
      "_ms\0309 \001(\005\022\026\n\007is_test\030\017 \001(\010:\005false\022\026\n\007is_" +
      "ping\030\021 \001(\010:\005false\022)\n\032is_predicted_to_be_" +
      "ignored\030- \001(\010:\005false\022-\n\014supply_chain\030E \001" +
      "(\0132\027.BidRequest.SupplyChain\022B\n\027frequency" +
      "_capping_scope\030F \001(\0162!.BidRequest.Freque" +
      "ncyCappingScope\032\351\001\n\021PrivacyTreatments\022_\n" +
      "\033non_personalized_ads_reason\030\006 \003(\01626.Bid" +
      "Request.PrivacyTreatments.NonPersonalize" +
      "dAdsReasonB\002\020\001\"s\n\030NonPersonalizedAdsReas" +
      "on\022\013\n\007UNKNOWN\020\000\022\032\n\026PUBLISHER_DECLARED_NP" +
      "A\020\001\022\034\n\030RESTRICT_DATA_PROCESSING\020\002\022\020\n\014USE" +
      "R_OPT_OUT\020\003\032\242\002\n\tUserAgent\0223\n\007browser\030\001 \001" +
      "(\0132\".BidRequest.UserAgent.BrandVersion\0224" +
      "\n\010browsers\030\010 \003(\0132\".BidRequest.UserAgent." +
      "BrandVersion\0224\n\010platform\030\002 \001(\0132\".BidRequ" +
      "est.UserAgent.BrandVersion\022\016\n\006mobile\030\003 \001" +
      "(\010\022\024\n\014architecture\030\004 \001(\t\022\017\n\007bitness\030\t \001(" +
      "\t\022\r\n\005model\030\005 \001(\t\032.\n\014BrandVersion\022\r\n\005bran" +
      "d\030\001 \001(\t\022\017\n\007version\030\002 \003(\t\032\217\001\n\003Geo\022\013\n\003lat\030" +
      "\001 \001(\001\022\013\n\003lon\030\002 \001(\001\022\017\n\007country\030\003 \001(\t\022\016\n\006r" +
      "egion\030\004 \001(\t\022\r\n\005metro\030\006 \001(\t\022\014\n\004city\030\007 \001(\t" +
      "\022\013\n\003zip\030\010 \001(\t\022\020\n\010accuracy\030\013 \001(\005\022\021\n\tutcof" +
      "fset\030\n \001(\005\032i\n\nHyperlocal\022-\n\007corners\030\001 \003(" +
      "\0132\034.BidRequest.Hyperlocal.Point\032,\n\005Point" +
      "\022\020\n\010latitude\030\001 \001(\002\022\021\n\tlongitude\030\002 \001(\002\032o\n" +
      "\rHyperlocalSet\022*\n\nhyperlocal\030\001 \003(\0132\026.Bid" +
      "Request.Hyperlocal\0222\n\014center_point\030\002 \001(\013" +
      "2\034.BidRequest.Hyperlocal.Point\032+\n\010UserLi" +
      "st\022\n\n\002id\030\001 \001(\003\022\023\n\013age_seconds\030\002 \001(\005\032&\n\010V" +
      "ertical\022\n\n\002id\030\001 \002(\005\022\016\n\006weight\030\002 \002(\002\032\371\006\n\006" +
      "Device\022B\n\013device_type\030\001 \001(\0162\035.BidRequest" +
      ".Device.DeviceType:\016UNKNOWN_DEVICE\022\022\n\010pl" +
      "atform\030\002 \001(\t:\000\022\017\n\005brand\030\003 \001(\t:\000\022\017\n\005model" +
      "\030\004 \001(\t:\000\0220\n\nos_version\030\005 \001(\0132\034.BidReques" +
      "t.Device.OsVersion\022\025\n\ncarrier_id\030\006 \001(\003:\001" +
      "0\022\027\n\014screen_width\030\007 \001(\005:\0010\022\030\n\rscreen_hei" +
      "ght\030\010 \001(\005:\0010\022$\n\031screen_pixel_ratio_milli" +
      "s\030\t \001(\005:\0010\022U\n\022screen_orientation\030\n \001(\0162$" +
      ".BidRequest.Device.ScreenOrientation:\023UN" +
      "KNOWN_ORIENTATION\022\030\n\020hardware_version\030\013 " +
      "\001(\t\022\031\n\021limit_ad_tracking\030\014 \001(\010\022Q\n!app_tr" +
      "acking_authorization_status\030\r \001(\0162&.BidR" +
      "equest.Device.AuthorizationStatus\032D\n\tOsV" +
      "ersion\022\021\n\005major\030\001 \001(\005:\002-1\022\021\n\005minor\030\002 \001(\005" +
      ":\002-1\022\021\n\005micro\030\003 \001(\005:\002-1\"\213\001\n\nDeviceType\022\022" +
      "\n\016UNKNOWN_DEVICE\020\000\022\021\n\rHIGHEND_PHONE\020\001\022\n\n" +
      "\006TABLET\020\002\022\025\n\021PERSONAL_COMPUTER\020\003\022\020\n\014CONN" +
      "ECTED_TV\020\004\022\020\n\014GAME_CONSOLE\020\005\022\017\n\013SET_TOP_" +
      "BOX\020\006\"I\n\021ScreenOrientation\022\027\n\023UNKNOWN_OR" +
      "IENTATION\020\000\022\014\n\010PORTRAIT\020\001\022\r\n\tLANDSCAPE\020\002" +
      "\"U\n\023AuthorizationStatus\022\022\n\016NOT_DETERMINE" +
      "D\020\000\022\016\n\nRESTRICTED\020\001\022\n\n\006DENIED\020\002\022\016\n\nAUTHO" +
      "RIZED\020\003\032&\n\010KeyValue\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t\032\235\006\n\006Mobile\022\025\n\006is_app\030\007 \001(\010:\005fals" +
      "e\022\016\n\006app_id\030\006 \001(\t\022&\n\027is_interstitial_req" +
      "uest\030\n \001(\010:\005false\022\030\n\020app_category_ids\030\013 " +
      "\003(\005\022&\n\027is_mobile_web_optimized\030\021 \001(\010:\005fa" +
      "lse\022 \n\030encrypted_advertising_id\030\024 \001(\014\022\026\n" +
      "\016advertising_id\030\033 \001(\014\022\035\n\025encrypted_hashe" +
      "d_idfa\030\025 \001(\014\022\023\n\013hashed_idfa\030\034 \001(\014\022\020\n\010app" +
      "_name\030\030 \001(\t\022\022\n\napp_rating\030\031 \001(\002\0226\n\rinsta" +
      "lled_sdk\030  \003(\0132\037.BidRequest.Mobile.Insta" +
      "lledSdk\0224\n\005skadn\030\" \001(\0132%.BidRequest.Mobi" +
      "le.SKAdNetworkRequest\032\336\001\n\014InstalledSdk\022\n" +
      "\n\002id\030\001 \001(\t\022<\n\013sdk_version\030\002 \001(\0132\'.BidReq" +
      "uest.Mobile.InstalledSdk.Version\022@\n\017adap" +
      "ter_version\030\003 \001(\0132\'.BidRequest.Mobile.In" +
      "stalledSdk.Version\032B\n\007Version\022\021\n\005major\030\001" +
      " \001(\005:\002-1\022\021\n\005minor\030\002 \001(\005:\002-1\022\021\n\005micro\030\003 \001" +
      "(\005:\002-1\032\236\001\n\022SKAdNetworkRequest\022\017\n\007version" +
      "\030\001 \001(\t\022\020\n\010versions\030\004 \003(\t\022\021\n\tsourceapp\030\002 " +
      "\001(\t\022\022\n\nskadnetids\030\003 \003(\t\022>\n\030supported_fid" +
      "elity_types\030\005 \003(\0162\030.SKAdNetworkFidelityT" +
      "ypeB\002\020\001\032\320\020\n\005Video\022A\n\tplacement\030\020 \001(\0162\033.B" +
      "idRequest.Video.Placement:\021UNKNOWN_PLACE" +
      "MENT\022\027\n\017description_url\030\n \001(\t\022\"\n\023is_embe" +
      "dded_offsite\030\013 \001(\010:\005false\022N\n\017playback_me" +
      "thod\030\016 \001(\0162%.BidRequest.Video.VideoPlayb" +
      "ackMethod:\016METHOD_UNKNOWN\022\024\n\014is_clickabl" +
      "e\030\017 \001(\010\022\033\n\023videoad_start_delay\030\001 \001(\005\022\027\n\017" +
      "max_ad_duration\030\002 \001(\005\022\027\n\017min_ad_duration" +
      "\030\010 \001(\005\022\026\n\016max_ads_in_pod\030\014 \001(\005\022V\n\022video_" +
      "ad_skippable\030\004 \001(\0162).BidRequest.Video.Sk" +
      "ippableBidRequestType:\017ALLOW_SKIPPABLE\022!" +
      "\n\031skippable_max_ad_duration\030\005 \001(\005\0226\n\tpro" +
      "tocols\030\021 \003(\0162\037.BidRequest.Video.VideoPro" +
      "tocolB\002\020\001\022<\n\025allowed_video_formats\030\006 \003(\016" +
      "2\035.BidRequest.Video.VideoFormat\0227\n\016compa" +
      "nion_slot\030\007 \003(\0132\037.BidRequest.Video.Compa" +
      "nionSlot\022M\n\017end_cap_support\030\r \001(\0162\037.BidR" +
      "equest.Video.EndCapSupport:\023END_CAP_NOT_" +
      "ENABLED\022?\n\022content_attributes\030\t \001(\0132#.Bi" +
      "dRequest.Video.ContentAttributes\022\034\n\ris_l" +
      "ivestream\030\022 \001(\010:\005false\032\362\001\n\rCompanionSlot" +
      "\022\022\n\006height\030\001 \003(\005B\002\020\001\022\021\n\005width\030\002 \003(\005B\002\020\001\022" +
      "G\n\017creative_format\030\003 \003(\0162..BidRequest.Vi" +
      "deo.CompanionSlot.CreativeFormat\"q\n\016Crea" +
      "tiveFormat\022$\n\027UNKNOWN_CREATIVE_FORMAT\020\377\377" +
      "\377\377\377\377\377\377\377\001\022\022\n\016IMAGE_CREATIVE\020\000\022\022\n\016FLASH_CR" +
      "EATIVE\020\001\022\021\n\rHTML_CREATIVE\020\002\032-\n\021ContentAt" +
      "tributes\022\030\n\020duration_seconds\030\002 \001(\005\"j\n\tPl" +
      "acement\022\025\n\021UNKNOWN_PLACEMENT\020\000\022\014\n\010INSTRE" +
      "AM\020\001\022\020\n\014INTERSTITIAL\020\002\022\013\n\007IN_FEED\020\003\022\t\n\005A" +
      "UDIO\020\004\022\016\n\nIN_ARTICLE\020\005\"\326\001\n\023VideoPlayback" +
      "Method\022\022\n\016METHOD_UNKNOWN\020\000\022\026\n\022AUTO_PLAY_" +
      "SOUND_ON\020\001\022\027\n\023AUTO_PLAY_SOUND_OFF\020\002\022\021\n\rC" +
      "LICK_TO_PLAY\020\003\022\016\n\nMOUSE_OVER\020\004\022*\n&INITIA" +
      "TE_ON_ENTERING_VIEWPORT_SOUND_ON\020\005\022+\n\'IN" +
      "ITIATE_ON_ENTERING_VIEWPORT_SOUND_OFF\020\006\"" +
      "Z\n\027SkippableBidRequestType\022\023\n\017ALLOW_SKIP" +
      "PABLE\020\000\022\025\n\021REQUIRE_SKIPPABLE\020\001\022\023\n\017BLOCK_" +
      "SKIPPABLE\020\002\"\341\001\n\rVideoProtocol\022\032\n\026UNKNOWN" +
      "_VIDEO_PROTOCOL\020\000\022\014\n\010VAST_1_0\020\001\022\014\n\010VAST_" +
      "2_0\020\002\022\014\n\010VAST_3_0\020\003\022\024\n\020VAST_1_0_WRAPPER\020" +
      "\004\022\024\n\020VAST_2_0_WRAPPER\020\005\022\024\n\020VAST_3_0_WRAP" +
      "PER\020\006\022\014\n\010VAST_4_0\020\007\022\024\n\020VAST_4_0_WRAPPER\020" +
      "\010\022\r\n\tDAAST_1_0\020\t\022\025\n\021DAAST_1_0_WRAPPER\020\n\"" +
      "\213\002\n\013VideoFormat\022!\n\024UNKNOWN_VIDEO_FORMAT\020" +
      "\377\377\377\377\377\377\377\377\377\001\022\r\n\tVIDEO_FLV\020\000\022\r\n\tVIDEO_MP4\020\001" +
      "\022\r\n\tYT_HOSTED\020\002\022\017\n\013VPAID_FLASH\020\003\022\014\n\010VPAI" +
      "D_JS\020\004\022\r\n\tAUDIO_MP3\020\005\022\r\n\tAUDIO_OGG\020\006\022\021\n\r" +
      "AUDIO_MP3_OGG\020\007\022\016\n\nVIDEO_WEBM\020\010\022\r\n\tVIDEO" +
      "_MOV\020\t\022\016\n\nVIDEO_3GPP\020\n\022\r\n\tVIDEO_HLS\020\013\022\016\n" +
      "\nVIDEO_DASH\020\014\022\016\n\nAUDIO_MP4A\020\r\"k\n\rEndCapS" +
      "upport\022\027\n\023END_CAP_NOT_ENABLED\020\000\022\024\n\020END_C" +
      "AP_OPTIONAL\020\001\022\025\n\021END_CAP_FORBIDDEN\020\002\022\024\n\020" +
      "END_CAP_REQUIRED\020\003\032\3269\n\006AdSlot\022\n\n\002id\030\001 \002(" +
      "\005\022\024\n\014ad_block_key\030\016 \001(\004\022\032\n\022targetable_ch" +
      "annel\030\n \003(\t\022\r\n\005width\030\002 \003(\005\022\016\n\006height\030\003 \003" +
      "(\005\022K\n\030flexible_adslot_settings\0302 \001(\0132).B" +
      "idRequest.AdSlot.FlexibleAdSlotSettings\022" +
      "\036\n\022excluded_attribute\030\004 \003(\005B\002\020\001\022\037\n\023allow" +
      "ed_vendor_type\030\006 \003(\005B\002\020\001\022S\n\034consented_pr" +
      "oviders_settings\030* \001(\0132-.BidRequest.AdSl" +
      "ot.ConsentedProvidersSettings\022\021\n\tregs_gd" +
      "pr\030+ \001(\010\022\021\n\tregs_lgpd\0306 \001(\010\022\'\n\033excluded_" +
      "sensitive_category\030\007 \003(\005B\002\020\001\022\'\n\033allowed_" +
      "restricted_category\030\020 \003(\005B\002\020\001\0221\n%allowed" +
      "_restricted_category_for_deals\030\026 \003(\005B\002\020\001" +
      "\022\031\n\021allowed_languages\030\033 \003(\t\022%\n\031excluded_" +
      "product_category\030\r \003(\005B\002\020\001\022?\n\022excluded_c" +
      "reatives\030\022 \003(\0132#.BidRequest.AdSlot.Exclu" +
      "dedCreative\022\037\n\027only_deal_bids_accepted\0301" +
      " \001(\010\022;\n\020matching_ad_data\030\t \003(\0132!.BidRequ" +
      "est.AdSlot.MatchingAdData\022\"\n\032publisher_s" +
      "ettings_list_id\030\017 \003(\006\022<\n\020exchange_biddin" +
      "g\030\034 \001(\0132\".BidRequest.AdSlot.ExchangeBidd" +
      "ing\0224\n\014open_bidding\0305 \001(\0132\036.BidRequest.A" +
      "dSlot.OpenBidding\022U\n\035creative_enforcemen" +
      "t_settings\030: \001(\0132..BidRequest.AdSlot.Cre" +
      "ativeEnforcementSettings\022\030\n\020dfp_ad_unit_" +
      "code\030! \001(\t\022H\n\017slot_visibility\030\014 \001(\0162!.Bi" +
      "dRequest.AdSlot.SlotVisibility:\014NO_DETEC" +
      "TION\022\027\n\013viewability\030\025 \001(\005:\002-1\022\036\n\022click_t" +
      "hrough_rate\030\031 \001(\002:\002-1\022!\n\025video_completio" +
      "n_rate\030\036 \001(\002:\002-1\022N\n\016iframing_state\030\023 \001(\016" +
      "2 .BidRequest.AdSlot.IFramingState:\024UNKN" +
      "OWN_IFRAME_STATE\022N\n\016iframing_depth\030\024 \001(\016" +
      "2 .BidRequest.AdSlot.IFramingDepth:\024UNKN" +
      "OWN_IFRAME_DEPTH\022?\n\022native_ad_template\0303" +
      " \003(\0132#.BidRequest.AdSlot.NativeAdTemplat" +
      "e\022X\n\025native_placement_type\030- \001(\0162&.BidRe" +
      "quest.AdSlot.NativePlacementType:\021PLACEM" +
      "ENT_UNKNOWN\022E\n\020mediation_status\0304 \001(\0162\"." +
      "BidRequest.AdSlot.MediationStatus:\007UNKNO" +
      "WN\0224\n\014auto_refresh\030\027 \001(\0132\036.BidRequest.Ad" +
      "Slot.AutoRefresh\022:\n\017sticky_settings\030\037 \001(" +
      "\0132!.BidRequest.AdSlot.StickySettings\022W\n\027" +
      "non_browser_slot_source\030\" \001(\0162#.BidReque" +
      "st.AdSlot.NonBrowserSource:\021UNDECLARED_S" +
      "OURCE\022?\n\010renderer\030\032 \001(\0162\033.BidRequest.AdS" +
      "lot.Renderer:\020UNKNOWN_RENDERER\022N\n\023amp_ad" +
      "_request_type\030\035 \001(\0162#.BidRequest.AdSlot." +
      "AmpAdRequestType:\014NON_AMP_PAGE\022/\n\013is_amp" +
      "_page\030& \001(\0162\032.BidRequest.AdSlot.AmpPage\022" +
      "H\n\027amp_ad_requirement_type\030\' \001(\0162\'.BidRe" +
      "quest.AdSlot.AmpAdRequirementType\022\032\n\013is_" +
      "rewarded\030  \001(\010:\005false\022>\n\020allowed_ad_type" +
      "s\030$ \003(\0162 .BidRequest.AdSlot.AllowedAdTyp" +
      "eB\002\020\001\022\031\n\rsession_depth\030( \001(\005:\002-1\022R\n\034buye" +
      "r_generated_request_data\030) \003(\0132,.BidRequ" +
      "est.AdSlot.BuyerGeneratedRequestData\0220\n\003" +
      "api\030. \003(\0162\037.BidRequest.AdSlot.APIFramewo" +
      "rkB\002\020\001\022)\n\036billable_event_rate_adjustment" +
      "\030; \001(\001:\0011\022@\n\023multi_ads_cell_info\0307 \001(\0132#" +
      ".BidRequest.AdSlot.MultiAdsCellInfo\022\016\n\006o" +
      "midpn\0308 \001(\t\022\016\n\006omidpv\0309 \001(\t\022W\n\023auction_e" +
      "nvironment\030= \001(\0162%.BidRequest.AdSlot.Auc" +
      "tionEnvironment:\023SERVER_SIDE_AUCTION\032f\n\026" +
      "FlexibleAdSlotSettings\022\021\n\tmax_width\030\001 \001(" +
      "\005\022\022\n\nmax_height\030\002 \001(\005\022\021\n\tmin_width\030\003 \001(\005" +
      "\022\022\n\nmin_height\030\004 \001(\005\032|\n\032ConsentedProvide" +
      "rsSettings\022\037\n\023consented_providers\030\002 \003(\003B" +
      "\002\020\001\022\032\n\022tcf_consent_string\030\003 \001(\t\022!\n\031addit" +
      "ional_consent_string\030\004 \001(\t\032-\n\020ExcludedCr" +
      "eative\022\031\n\021buyer_creative_id\030\001 \001(\t\032\317\005\n\016Ma" +
      "tchingAdData\022\026\n\nbilling_id\030\002 \003(\003B\002\020\000\022\032\n\022" +
      "minimum_cpm_micros\030\005 \001(\003\022A\n\013direct_deal\030" +
      "\006 \003(\0132,.BidRequest.AdSlot.MatchingAdData" +
      ".DirectDeal\032\305\004\n\nDirectDeal\022\026\n\016direct_dea" +
      "l_id\030\001 \001(\003\022\030\n\020fixed_cpm_micros\030\002 \001(\003\022[\n\t" +
      "deal_type\030\003 \001(\01625.BidRequest.AdSlot.Matc" +
      "hingAdData.DirectDeal.DealType:\021UNKNOWN_" +
      "DEAL_TYPE\022*\n\033publisher_blocks_overridden" +
      "\030\004 \001(\010:\005false\022t\n\017creative_source\030\020 \001(\0162?" +
      ".BidRequest.AdSlot.MatchingAdData.Direct" +
      "Deal.CreativeSourceType:\032CREATIVE_SOURCE" +
      "_ADVERTISER\022\026\n\010must_bid\030\t \001(\010:\004true\"|\n\010D" +
      "ealType\022\025\n\021UNKNOWN_DEAL_TYPE\020\000\022\022\n\016PREFER" +
      "RED_DEAL\020\001\022\023\n\017PRIVATE_AUCTION\020\002\022\033\n\027PROGR" +
      "AMMATIC_GUARANTEED\020\003\022\023\n\017AUCTION_PACKAGE\020" +
      "\004\"p\n\022CreativeSourceType\022\033\n\027CREATIVE_SOUR" +
      "CE_UNKNOWN\020\000\022\036\n\032CREATIVE_SOURCE_ADVERTIS" +
      "ER\020\001\022\035\n\031CREATIVE_SOURCE_PUBLISHER\020\002\032:\n\017E" +
      "xchangeBidding\022\'\n\tkey_value\030\003 \003(\0132\024.BidR" +
      "equest.KeyValue\032&\n\013OpenBidding\022\027\n\017is_ope" +
      "n_bidding\030\002 \001(\010\032\262\004\n\033CreativeEnforcementS" +
      "ettings\022\\\n\022policy_enforcement\030\001 \001(\0162@.Bi" +
      "dRequest.AdSlot.CreativeEnforcementSetti" +
      "ngs.PolicyEnforcement\022o\n\034publisher_block" +
      "s_enforcement\030\003 \001(\0162I.BidRequest.AdSlot." +
      "CreativeEnforcementSettings.PublisherBlo" +
      "cksEnforcement\022\022\n\nis_default\030\004 \001(\010\"\217\001\n\021P" +
      "olicyEnforcement\022\036\n\032POLICY_ENFORCEMENT_U" +
      "NKNOWN\020\000\022&\n\"POLICY_ENFORCEMENT_PLATFORM_" +
      "POLICY\020\001\0222\n.POLICY_ENFORCEMENT_NETWORK_A" +
      "ND_PLATFORM_POLICY\020\002\"\235\001\n\032PublisherBlocks" +
      "Enforcement\022(\n$PUBLISHER_BLOCKS_ENFORCEM" +
      "ENT_UNKNOWN\020\000\022(\n$PUBLISHER_BLOCKS_ENFORC" +
      "EMENT_APPLIES\020\001\022+\n\'PUBLISHER_BLOCKS_ENFO" +
      "RCEMENT_OVERRIDDEN\020\002\032\344\005\n\020NativeAdTemplat" +
      "e\022\027\n\017required_fields\030\001 \001(\003\022\032\n\022recommende" +
      "d_fields\030\002 \001(\003\022 \n\030headline_max_safe_leng" +
      "th\030\003 \001(\005\022\034\n\024body_max_safe_length\030\004 \001(\005\022&" +
      "\n\036call_to_action_max_safe_length\030\005 \001(\005\022\"" +
      "\n\032advertiser_max_safe_length\030\006 \001(\005\022\035\n\025pr" +
      "ice_max_safe_length\030\017 \001(\005\022\023\n\013image_width" +
      "\030\007 \001(\005\022\024\n\014image_height\030\010 \001(\005\022\022\n\nlogo_wid" +
      "th\030\t \001(\005\022\023\n\013logo_height\030\n \001(\005\022\026\n\016app_ico" +
      "n_width\030\013 \001(\005\022\027\n\017app_icon_height\030\014 \001(\005\022\020" +
      "\n\010style_id\030\020 \001(\005\022P\n\021style_layout_type\030\021 " +
      "\001(\0162..BidRequest.AdSlot.NativeAdTemplate" +
      ".LayoutType:\005PIXEL\022\024\n\014style_height\030\022 \001(\005" +
      "\022\023\n\013style_width\030\023 \001(\005\"\267\001\n\006Fields\022\r\n\tNO_F" +
      "IELDS\020\000\022\014\n\010HEADLINE\020\001\022\010\n\004BODY\020\002\022\022\n\016CALL_" +
      "TO_ACTION\020\004\022\016\n\nADVERTISER\020\010\022\t\n\005IMAGE\020\020\022\010" +
      "\n\004LOGO\020 \022\014\n\010APP_ICON\020@\022\020\n\013STAR_RATING\020\200\001" +
      "\022\n\n\005PRICE\020\200\002\022\025\n\020DEPRECATED_STORE\020\200\004\022\n\n\005V" +
      "IDEO\020\200\010\"\"\n\nLayoutType\022\t\n\005PIXEL\020\000\022\t\n\005FLUI" +
      "D\020\001\032\200\003\n\013AutoRefresh\022L\n\020refresh_settings\030" +
      "\001 \003(\01322.BidRequest.AdSlot.AutoRefresh.Au" +
      "toRefreshSettings\022\030\n\rrefresh_count\030\002 \001(\005" +
      ":\0010\032\210\002\n\023AutoRefreshSettings\022s\n\014refresh_t" +
      "ype\030\001 \001(\0162B.BidRequest.AdSlot.AutoRefres" +
      "h.AutoRefreshSettings.AutoRefreshType:\031U" +
      "NKNOWN_AUTO_REFRESH_TYPE\022$\n\034min_refresh_" +
      "interval_seconds\030\002 \001(\005\"V\n\017AutoRefreshTyp" +
      "e\022\035\n\031UNKNOWN_AUTO_REFRESH_TYPE\020\000\022\017\n\013USER" +
      "_ACTION\020\001\022\t\n\005EVENT\020\002\022\010\n\004TIME\020\003\032\361\002\n\016Stick" +
      "ySettings\022]\n\023vertical_stickiness\030\001 \001(\0162," +
      ".BidRequest.AdSlot.StickySettings.Sticki" +
      "ness:\022UNKNOWN_STICKINESS\022c\n\031top_horizont" +
      "al_stickiness\030\002 \001(\0162,.BidRequest.AdSlot." +
      "StickySettings.Stickiness:\022UNKNOWN_STICK" +
      "INESS\022f\n\034bottom_horizontal_stickiness\030\003 " +
      "\001(\0162,.BidRequest.AdSlot.StickySettings.S" +
      "tickiness:\022UNKNOWN_STICKINESS\"3\n\nStickin" +
      "ess\022\026\n\022UNKNOWN_STICKINESS\020\000\022\r\n\tIS_STICKY" +
      "\020\001\032\376\001\n\031BuyerGeneratedRequestData\022L\n\nsour" +
      "ce_app\030\001 \001(\01326.BidRequest.AdSlot.BuyerGe" +
      "neratedRequestData.SourceAppH\000\022J\n\tsource" +
      "_js\030\003 \001(\01325.BidRequest.AdSlot.BuyerGener" +
      "atedRequestData.SourceJsH\000\022\014\n\004data\030\002 \001(\t" +
      "\032\027\n\tSourceApp\022\n\n\002id\030\001 \001(\t\032\026\n\010SourceJs\022\n\n" +
      "\002id\030\001 \001(\tB\010\n\006source\032s\n\020MultiAdsCellInfo\022" +
      "\020\n\010cell_row\030\001 \001(\005\022\023\n\013cell_column\030\002 \001(\005\022\021" +
      "\n\tgrid_rows\030\003 \001(\005\022\024\n\014grid_columns\030\004 \001(\005\022" +
      "\017\n\007grid_id\030\005 \001(\003\"J\n\016SlotVisibility\022\020\n\014NO" +
      "_DETECTION\020\000\022\022\n\016ABOVE_THE_FOLD\020\001\022\022\n\016BELO" +
      "W_THE_FOLD\020\002\"i\n\rIFramingState\022\030\n\024UNKNOWN" +
      "_IFRAME_STATE\020\000\022\r\n\tNO_IFRAME\020\001\022\026\n\022SAME_D" +
      "OMAIN_IFRAME\020\002\022\027\n\023CROSS_DOMAIN_IFRAME\020\003\"" +
      "a\n\rIFramingDepth\022\030\n\024UNKNOWN_IFRAME_DEPTH" +
      "\020\000\022\021\n\rNOT_IN_IFRAME\020\001\022\016\n\nONE_IFRAME\020\002\022\023\n" +
      "\017MULTIPLE_IFRAME\020\003\"\223\001\n\023NativePlacementTy" +
      "pe\022\025\n\021PLACEMENT_UNKNOWN\020\000\022\025\n\021PLACEMENT_I" +
      "N_FEED\020\001\022\031\n\025PLACEMENT_ATOMIC_UNIT\020\002\022\025\n\021P" +
      "LACEMENT_OUTSIDE\020\003\022\034\n\030PLACEMENT_RECOMMEN" +
      "DATION\020\004\"2\n\017MediationStatus\022\013\n\007UNKNOWN\020\000" +
      "\022\022\n\016DIRECT_REQUEST\020\001\":\n\020NonBrowserSource" +
      "\022\025\n\021UNDECLARED_SOURCE\020\000\022\017\n\013DESKTOP_APP\020\001" +
      "\";\n\010Renderer\022\024\n\020UNKNOWN_RENDERER\020\000\022\n\n\006GO" +
      "OGLE\020\001\022\r\n\tPUBLISHER\020\002\"P\n\020AmpAdRequestTyp" +
      "e\022\017\n\013UNKNOWN_AMP\020\000\022\020\n\014NON_AMP_PAGE\020\001\022\031\n\025" +
      "AMP_PAGE_LATE_REQUEST\020\002\"G\n\007AmpPage\022\024\n\020UN" +
      "KNOWN_AMP_PAGE\020\000\022\020\n\014DIALECT_HTML\020\001\022\024\n\020DI" +
      "ALECT_HTML_AMP\020\002\"\272\001\n\024AmpAdRequirementTyp" +
      "e\022#\n\037UNKNOWN_AMP_AD_REQUIREMENT_TYPE\020\000\022\026" +
      "\n\022AMP_AD_NOT_ALLOWED\020\001\022)\n%AMP_AD_ALLOWED" +
      "_AND_NOT_EARLY_RENDERED\020\002\022%\n!AMP_AD_ALLO" +
      "WED_AND_EARLY_RENDERED\020\003\022\023\n\017AMP_AD_REQUI" +
      "RED\020\004\"\243\001\n\rAllowedAdType\022$\n\027UNKNOWN_ALLOW" +
      "ED_AD_TYPE\020\377\377\377\377\377\377\377\377\377\001\022\032\n\026ALLOWED_AD_TYPE" +
      "_BANNER\020\000\022\032\n\026ALLOWED_AD_TYPE_NATIVE\020\001\022\031\n" +
      "\025ALLOWED_AD_TYPE_VIDEO\020\002\022\031\n\025ALLOWED_AD_T" +
      "YPE_AUDIO\020\003\"X\n\014APIFramework\022\025\n\021UNKNOWN_F" +
      "RAMEWORK\020\000\022\013\n\007MRAID_1\020\003\022\013\n\007MRAID_2\020\005\022\013\n\007" +
      "MRAID_3\020\006\022\n\n\006OMID_1\020\007\"\213\001\n\022AuctionEnviron" +
      "ment\022\027\n\023SERVER_SIDE_AUCTION\020\000\022$\n ON_DEVI" +
      "CE_INTEREST_GROUP_AUCTION\020\001\0226\n2SERVER_SI" +
      "DE_AUCTION_WITH_INTEREST_GROUP_SIMULATIO" +
      "N\020\002\032\203\002\n\023BidResponseFeedback\022\022\n\nrequest_i" +
      "d\030\001 \001(\014\022\026\n\016creative_index\030\002 \001(\005\022\034\n\024creat" +
      "ive_status_code\030\003 \001(\005\022\022\n\ncpm_micros\030\004 \001(" +
      "\003\022\032\n\022minimum_bid_to_win\030\007 \001(\003\0225\n-sampled" +
      "_mediation_cpm_ahead_of_auction_winner\030\n" +
      " \001(\003\022 \n\030event_notification_token\030\005 \001(\014\022\031" +
      "\n\021buyer_creative_id\030\006 \001(\t\032\326\001\n\013SupplyChai" +
      "n\022\020\n\010complete\030\001 \001(\010\0226\n\005nodes\030\002 \003(\0132\'.Bid" +
      "Request.SupplyChain.SupplyChainNode\022\017\n\007v" +
      "ersion\030\003 \001(\t\032l\n\017SupplyChainNode\022%\n\035adver" +
      "tising_system_identifier\030\001 \001(\t\022\031\n\021seller" +
      "_identifier\030\002 \001(\t\022\027\n\017handles_payment\030\006 \001" +
      "(\010\"9\n\021UserDataTreatment\022$\n TAG_FOR_CHILD" +
      "_DIRECTED_TREATMENT\020\000\"[\n\013AuctionType\022\030\n\024" +
      "UNKNOWN_AUCTION_TYPE\020\000\022\017\n\013FIRST_PRICE\020\001\022" +
      "\020\n\014SECOND_PRICE\020\002\022\017\n\013FIXED_PRICE\020\003\"\217\001\n\rP" +
      "ublisherType\022\032\n\026UNKNOWN_PUBLISHER_TYPE\020\000" +
      "\022 \n\034PUBLISHER_OWNED_AND_OPERATED\020\001\022\031\n\025PU" +
      "BLISHER_REPRESENTED\020\002\022%\n\035DEPRECATED_GOOG" +
      "LE_REPRESENTED\020\003\032\002\010\001\"j\n\017VisibilityState\022" +
      "\034\n\030VISIBILITY_STATE_UNKNOWN\020\000\022\034\n\030VISIBIL" +
      "ITY_STATE_VISIBLE\020\001\022\033\n\027VISIBILITY_STATE_" +
      "HIDDEN\020\002\"\352\001\n\025FrequencyCappingScope\022#\n\037FR" +
      "EQUENCY_CAPPING_SCOPE_UNKNOWN\020\000\022 \n\034FREQU" +
      "ENCY_CAPPING_SCOPE_NONE\020\001\022#\n\037FREQUENCY_C" +
      "APPING_SCOPE_BROWSER\020\002\022\"\n\036FREQUENCY_CAPP" +
      "ING_SCOPE_DEVICE\020\003\022\037\n\033FREQUENCY_CAPPING_" +
      "SCOPE_APP\020\004\022 \n\034FREQUENCY_CAPPING_SCOPE_S" +
      "ITE\020\005\"\312\027\n\013BidResponse\022\033\n\002ad\030\002 \003(\0132\017.BidR" +
      "esponse.Ad\022\024\n\014debug_string\030\005 \001(\t\022\032\n\022proc" +
      "essing_time_ms\030\004 \001(\005\022\025\n\rno_bid_reason\030\006 " +
      "\001(\005\032\324\026\n\002Ad\022 \n\030event_notification_token\030\031" +
      " \001(\014\022\031\n\021buyer_creative_id\030\n \001(\t\022\024\n\014html_" +
      "snippet\030\001 \001(\t\022\021\n\tvideo_url\030\t \001(\t\022\026\n\016vide" +
      "o_vast_xml\030\030 \001(\t\022\022\n\namp_ad_url\030\027 \001(\t\022+\n\t" +
      "native_ad\030\022 \001(\0132\030.BidResponse.Ad.NativeA" +
      "d\022\031\n\021click_through_url\030\004 \003(\t\022\023\n\013vendor_t" +
      "ype\030\005 \003(\005\022\021\n\tattribute\030\006 \003(\005\022\020\n\010category" +
      "\030\007 \003(\005\022\033\n\023restricted_category\030\021 \003(\005\022\027\n\017a" +
      "dvertiser_name\030\013 \003(\t\022\"\n\026DEPRECATED_bidde" +
      "r_name\030\026 \001(\tB\002\030\001\022\r\n\005width\030\016 \001(\005\022\016\n\006heigh" +
      "t\030\017 \001(\005\022\021\n\tagency_id\030\020 \001(\003\022&\n\006adslot\030\003 \003" +
      "(\0132\026.BidResponse.Ad.AdSlot\022\037\n\027impression" +
      "_tracking_url\030\023 \003(\t\022\033\n\023click_tracking_ur" +
      "ls\030\036 \003(\t\022\"\n\032ad_choices_destination_url\030\025" +
      " \001(\t\022P\n\034impression_tracking_resource\030\032 \003" +
      "(\0132*.BidResponse.Ad.ImpressionTrackingRe" +
      "source\0226\n\017sdk_rendered_ad\030\033 \001(\0132\035.BidRes" +
      "ponse.Ad.SdkRenderedAd\0222\n\005skadn\030\035 \001(\0132#." +
      "BidResponse.Ad.SKAdNetworkResponse\032\345\003\n\010N" +
      "ativeAd\022\020\n\010headline\030\001 \001(\t\022\014\n\004body\030\002 \001(\t\022",
      "\026\n\016call_to_action\030\003 \001(\t\022\022\n\nadvertiser\030\004 " +
      "\001(\t\022-\n\005image\030\005 \001(\0132\036.BidResponse.Ad.Nati" +
      "veAd.Image\022,\n\004logo\030\006 \001(\0132\036.BidResponse.A" +
      "d.NativeAd.Image\0220\n\010app_icon\030\007 \001(\0132\036.Bid" +
      "Response.Ad.NativeAd.Image\022\023\n\tvideo_url\030" +
      "\r \001(\tH\000\022\030\n\016video_vast_xml\030\020 \001(\tH\000\022\023\n\013sta" +
      "r_rating\030\010 \001(\001\022\026\n\016click_link_url\030\016 \001(\t\022)" +
      "\n\035DEPRECATED_click_tracking_url\030\013 \001(\tB\002\030" +
      "\001\022*\n\036DEPRECATED_click_tracking_urls\030\017 \003(" +
      "\tB\002\030\001\022\r\n\005price\030\n \001(\t\0323\n\005Image\022\013\n\003url\030\001 \001" +
      "(\t\022\r\n\005width\030\002 \001(\005\022\016\n\006height\030\003 \001(\005B\007\n\005vid" +
      "eo\032\270\005\n\006AdSlot\022\n\n\002id\030\001 \002(\005\022\026\n\016max_cpm_mic" +
      "ros\030\002 \002(\003\022\026\n\016min_cpm_micros\030\003 \001(\003\022\022\n\nbil" +
      "ling_id\030\004 \001(\003\022\022\n\007deal_id\030\005 \001(\003:\0010\022\030\n\020exc" +
      "hange_deal_id\030\006 \001(\t\022Q\n\022exchange_deal_typ" +
      "e\030\007 \001(\0162\'.BidResponse.Ad.AdSlot.Exchange" +
      "DealType:\014OPEN_AUCTION\022\032\n\022buyer_reportin" +
      "g_id\030\010 \001(\t\022\037\n\027third_party_buyer_token\030\014 " +
      "\001(\t\022:\n\rfrequency_cap\030\020 \003(\0132#.BidResponse" +
      ".Ad.AdSlot.FrequencyCap\032\366\001\n\014FrequencyCap" +
      "\022\030\n\020frequency_cap_id\030\001 \001(\t\022?\n\ttime_unit\030" +
      "\002 \001(\0162,.BidResponse.Ad.AdSlot.FrequencyC" +
      "ap.TimeUnit\022\025\n\ntime_range\030\003 \001(\005:\0011\022\027\n\017ma" +
      "x_impressions\030\004 \001(\005\"[\n\010TimeUnit\022\025\n\021UNKNO" +
      "WN_TIME_UNIT\020\000\022\n\n\006MINUTE\020\001\022\007\n\003DAY\020\002\022\010\n\004W" +
      "EEK\020\003\022\t\n\005MONTH\020\004\022\016\n\nINDEFINITE\020\005\"k\n\020Exch" +
      "angeDealType\022\020\n\014OPEN_AUCTION\020\000\022\023\n\017PRIVAT" +
      "E_AUCTION\020\001\022\022\n\016PREFERRED_DEAL\020\002\022\034\n\030EXCHA" +
      "NGE_AUCTION_PACKAGE\020\003\032\324\001\n\032ImpressionTrac" +
      "kingResource\022\022\n\nscript_url\030\001 \001(\t\022C\n\007cont" +
      "ext\030\002 \003(\01622.BidResponse.Ad.ImpressionTra" +
      "ckingResource.Context\022\037\n\027verification_pa" +
      "rameters\030\003 \001(\t\022\022\n\nvendor_key\030\004 \001(\t\"(\n\007Co" +
      "ntext\022\023\n\017UNKNOWN_CONTEXT\020\000\022\010\n\004OMID\020\001\032\355\001\n" +
      "\rSdkRenderedAd\022\n\n\002id\030\001 \001(\t\022\026\n\016rendering_" +
      "data\030\002 \001(\t\022=\n\013declared_ad\030\006 \001(\0132(.BidRes" +
      "ponse.Ad.SdkRenderedAd.DeclaredAd\032y\n\nDec" +
      "laredAd\022\026\n\014html_snippet\030\001 \001(\tH\000\022\023\n\tvideo" +
      "_url\030\002 \001(\tH\000\022\030\n\016video_vast_xml\030\005 \001(\tH\000\022\031" +
      "\n\021click_through_url\030\004 \003(\tB\t\n\007content\032\373\003\n" +
      "\023SKAdNetworkResponse\022\017\n\007version\030\001 \001(\t\022\017\n" +
      "\007network\030\002 \001(\t\022\020\n\010campaign\030\003 \001(\003\022\022\n\nitun" +
      "esitem\030\004 \001(\t\022@\n\nfidelities\030\t \003(\0132,.BidRe" +
      "sponse.Ad.SKAdNetworkResponse.Fidelity\022\r" +
      "\n\005nonce\030\005 \001(\t\022\021\n\tsourceapp\030\006 \001(\t\022\021\n\ttime" +
      "stamp\030\007 \001(\003\022\021\n\tsignature\030\010 \001(\t\022M\n\rskadn_" +
      "options\030\n \001(\01326.BidResponse.Ad.SKAdNetwo" +
      "rkResponse.SKAdNetworkOptions\032\207\001\n\010Fideli" +
      "ty\022F\n\rfidelity_type\030\001 \001(\0162\030.SKAdNetworkF" +
      "idelityType:\025STOREKIT_RENDERED_ADS\022\r\n\005no" +
      "nce\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\022\021\n\tsignatur" +
      "e\030\004 \001(\t\0329\n\022SKAdNetworkOptions\022#\n\024always_" +
      "open_appstore\030\001 \001(\010:\005false*J\n\027SKAdNetwor" +
      "kFidelityType\022\024\n\020VIEW_THROUGH_ADS\020\000\022\031\n\025S" +
      "TOREKIT_RENDERED_ADS\020\001B\037\n\033com.example.pr" +
      "otobuf.googleP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_BidRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_descriptor,
        new java.lang.String[] { "Id", "Ip", "UserDataTreatment", "GoogleUserId", "CookieVersion", "CookieAgeSeconds", "HostedMatchData", "SessionId", "UserAgent", "PrivacyTreatments", "UserAgentData", "PublisherCountry", "HostPublisherId", "GeoCriteriaId", "Geo", "PostalCode", "PostalCodePrefix", "EncryptedHyperlocalSet", "HyperlocalSet", "TimezoneOffset", "UserList", "PublisherId", "SellerNetworkId", "PartnerId", "Url", "IsSemiTransparentRequest", "DetectedLanguage", "DetectedVertical", "DetectedContentLabel", "GoogleQueryId", "AuctionType", "Device", "KeyValue", "Mobile", "Video", "PublisherSettingsListId", "PublisherType", "PageVisibility", "Adslot", "BidResponseFeedback", "ResponseDeadlineMs", "IsTest", "IsPing", "IsPredictedToBeIgnored", "SupplyChain", "FrequencyCappingScope", });
    internal_static_BidRequest_PrivacyTreatments_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_PrivacyTreatments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_PrivacyTreatments_descriptor,
        new java.lang.String[] { "NonPersonalizedAdsReason", });
    internal_static_BidRequest_UserAgent_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(1);
    internal_static_BidRequest_UserAgent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_UserAgent_descriptor,
        new java.lang.String[] { "Browser", "Browsers", "Platform", "Mobile", "Architecture", "Bitness", "Model", });
    internal_static_BidRequest_UserAgent_BrandVersion_descriptor =
      internal_static_BidRequest_UserAgent_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_UserAgent_BrandVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_UserAgent_BrandVersion_descriptor,
        new java.lang.String[] { "Brand", "Version", });
    internal_static_BidRequest_Geo_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(2);
    internal_static_BidRequest_Geo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Geo_descriptor,
        new java.lang.String[] { "Lat", "Lon", "Country", "Region", "Metro", "City", "Zip", "Accuracy", "Utcoffset", });
    internal_static_BidRequest_Hyperlocal_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(3);
    internal_static_BidRequest_Hyperlocal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Hyperlocal_descriptor,
        new java.lang.String[] { "Corners", });
    internal_static_BidRequest_Hyperlocal_Point_descriptor =
      internal_static_BidRequest_Hyperlocal_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_Hyperlocal_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Hyperlocal_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_BidRequest_HyperlocalSet_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(4);
    internal_static_BidRequest_HyperlocalSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_HyperlocalSet_descriptor,
        new java.lang.String[] { "Hyperlocal", "CenterPoint", });
    internal_static_BidRequest_UserList_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(5);
    internal_static_BidRequest_UserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_UserList_descriptor,
        new java.lang.String[] { "Id", "AgeSeconds", });
    internal_static_BidRequest_Vertical_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(6);
    internal_static_BidRequest_Vertical_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Vertical_descriptor,
        new java.lang.String[] { "Id", "Weight", });
    internal_static_BidRequest_Device_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(7);
    internal_static_BidRequest_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Device_descriptor,
        new java.lang.String[] { "DeviceType", "Platform", "Brand", "Model", "OsVersion", "CarrierId", "ScreenWidth", "ScreenHeight", "ScreenPixelRatioMillis", "ScreenOrientation", "HardwareVersion", "LimitAdTracking", "AppTrackingAuthorizationStatus", });
    internal_static_BidRequest_Device_OsVersion_descriptor =
      internal_static_BidRequest_Device_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_Device_OsVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Device_OsVersion_descriptor,
        new java.lang.String[] { "Major", "Minor", "Micro", });
    internal_static_BidRequest_KeyValue_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(8);
    internal_static_BidRequest_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_KeyValue_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_BidRequest_Mobile_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(9);
    internal_static_BidRequest_Mobile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Mobile_descriptor,
        new java.lang.String[] { "IsApp", "AppId", "IsInterstitialRequest", "AppCategoryIds", "IsMobileWebOptimized", "EncryptedAdvertisingId", "AdvertisingId", "EncryptedHashedIdfa", "HashedIdfa", "AppName", "AppRating", "InstalledSdk", "Skadn", });
    internal_static_BidRequest_Mobile_InstalledSdk_descriptor =
      internal_static_BidRequest_Mobile_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_Mobile_InstalledSdk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Mobile_InstalledSdk_descriptor,
        new java.lang.String[] { "Id", "SdkVersion", "AdapterVersion", });
    internal_static_BidRequest_Mobile_InstalledSdk_Version_descriptor =
      internal_static_BidRequest_Mobile_InstalledSdk_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_Mobile_InstalledSdk_Version_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Mobile_InstalledSdk_Version_descriptor,
        new java.lang.String[] { "Major", "Minor", "Micro", });
    internal_static_BidRequest_Mobile_SKAdNetworkRequest_descriptor =
      internal_static_BidRequest_Mobile_descriptor.getNestedTypes().get(1);
    internal_static_BidRequest_Mobile_SKAdNetworkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Mobile_SKAdNetworkRequest_descriptor,
        new java.lang.String[] { "Version", "Versions", "Sourceapp", "Skadnetids", "SupportedFidelityTypes", });
    internal_static_BidRequest_Video_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(10);
    internal_static_BidRequest_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Video_descriptor,
        new java.lang.String[] { "Placement", "DescriptionUrl", "IsEmbeddedOffsite", "PlaybackMethod", "IsClickable", "VideoadStartDelay", "MaxAdDuration", "MinAdDuration", "MaxAdsInPod", "VideoAdSkippable", "SkippableMaxAdDuration", "Protocols", "AllowedVideoFormats", "CompanionSlot", "EndCapSupport", "ContentAttributes", "IsLivestream", });
    internal_static_BidRequest_Video_CompanionSlot_descriptor =
      internal_static_BidRequest_Video_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_Video_CompanionSlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Video_CompanionSlot_descriptor,
        new java.lang.String[] { "Height", "Width", "CreativeFormat", });
    internal_static_BidRequest_Video_ContentAttributes_descriptor =
      internal_static_BidRequest_Video_descriptor.getNestedTypes().get(1);
    internal_static_BidRequest_Video_ContentAttributes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_Video_ContentAttributes_descriptor,
        new java.lang.String[] { "DurationSeconds", });
    internal_static_BidRequest_AdSlot_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(11);
    internal_static_BidRequest_AdSlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_descriptor,
        new java.lang.String[] { "Id", "AdBlockKey", "TargetableChannel", "Width", "Height", "FlexibleAdslotSettings", "ExcludedAttribute", "AllowedVendorType", "ConsentedProvidersSettings", "RegsGdpr", "RegsLgpd", "ExcludedSensitiveCategory", "AllowedRestrictedCategory", "AllowedRestrictedCategoryForDeals", "AllowedLanguages", "ExcludedProductCategory", "ExcludedCreatives", "OnlyDealBidsAccepted", "MatchingAdData", "PublisherSettingsListId", "ExchangeBidding", "OpenBidding", "CreativeEnforcementSettings", "DfpAdUnitCode", "SlotVisibility", "Viewability", "ClickThroughRate", "VideoCompletionRate", "IframingState", "IframingDepth", "NativeAdTemplate", "NativePlacementType", "MediationStatus", "AutoRefresh", "StickySettings", "NonBrowserSlotSource", "Renderer", "AmpAdRequestType", "IsAmpPage", "AmpAdRequirementType", "IsRewarded", "AllowedAdTypes", "SessionDepth", "BuyerGeneratedRequestData", "Api", "BillableEventRateAdjustment", "MultiAdsCellInfo", "Omidpn", "Omidpv", "AuctionEnvironment", });
    internal_static_BidRequest_AdSlot_FlexibleAdSlotSettings_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_AdSlot_FlexibleAdSlotSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_FlexibleAdSlotSettings_descriptor,
        new java.lang.String[] { "MaxWidth", "MaxHeight", "MinWidth", "MinHeight", });
    internal_static_BidRequest_AdSlot_ConsentedProvidersSettings_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(1);
    internal_static_BidRequest_AdSlot_ConsentedProvidersSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_ConsentedProvidersSettings_descriptor,
        new java.lang.String[] { "ConsentedProviders", "TcfConsentString", "AdditionalConsentString", });
    internal_static_BidRequest_AdSlot_ExcludedCreative_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(2);
    internal_static_BidRequest_AdSlot_ExcludedCreative_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_ExcludedCreative_descriptor,
        new java.lang.String[] { "BuyerCreativeId", });
    internal_static_BidRequest_AdSlot_MatchingAdData_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(3);
    internal_static_BidRequest_AdSlot_MatchingAdData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_MatchingAdData_descriptor,
        new java.lang.String[] { "BillingId", "MinimumCpmMicros", "DirectDeal", });
    internal_static_BidRequest_AdSlot_MatchingAdData_DirectDeal_descriptor =
      internal_static_BidRequest_AdSlot_MatchingAdData_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_AdSlot_MatchingAdData_DirectDeal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_MatchingAdData_DirectDeal_descriptor,
        new java.lang.String[] { "DirectDealId", "FixedCpmMicros", "DealType", "PublisherBlocksOverridden", "CreativeSource", "MustBid", });
    internal_static_BidRequest_AdSlot_ExchangeBidding_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(4);
    internal_static_BidRequest_AdSlot_ExchangeBidding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_ExchangeBidding_descriptor,
        new java.lang.String[] { "KeyValue", });
    internal_static_BidRequest_AdSlot_OpenBidding_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(5);
    internal_static_BidRequest_AdSlot_OpenBidding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_OpenBidding_descriptor,
        new java.lang.String[] { "IsOpenBidding", });
    internal_static_BidRequest_AdSlot_CreativeEnforcementSettings_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(6);
    internal_static_BidRequest_AdSlot_CreativeEnforcementSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_CreativeEnforcementSettings_descriptor,
        new java.lang.String[] { "PolicyEnforcement", "PublisherBlocksEnforcement", "IsDefault", });
    internal_static_BidRequest_AdSlot_NativeAdTemplate_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(7);
    internal_static_BidRequest_AdSlot_NativeAdTemplate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_NativeAdTemplate_descriptor,
        new java.lang.String[] { "RequiredFields", "RecommendedFields", "HeadlineMaxSafeLength", "BodyMaxSafeLength", "CallToActionMaxSafeLength", "AdvertiserMaxSafeLength", "PriceMaxSafeLength", "ImageWidth", "ImageHeight", "LogoWidth", "LogoHeight", "AppIconWidth", "AppIconHeight", "StyleId", "StyleLayoutType", "StyleHeight", "StyleWidth", });
    internal_static_BidRequest_AdSlot_AutoRefresh_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(8);
    internal_static_BidRequest_AdSlot_AutoRefresh_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_AutoRefresh_descriptor,
        new java.lang.String[] { "RefreshSettings", "RefreshCount", });
    internal_static_BidRequest_AdSlot_AutoRefresh_AutoRefreshSettings_descriptor =
      internal_static_BidRequest_AdSlot_AutoRefresh_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_AdSlot_AutoRefresh_AutoRefreshSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_AutoRefresh_AutoRefreshSettings_descriptor,
        new java.lang.String[] { "RefreshType", "MinRefreshIntervalSeconds", });
    internal_static_BidRequest_AdSlot_StickySettings_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(9);
    internal_static_BidRequest_AdSlot_StickySettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_StickySettings_descriptor,
        new java.lang.String[] { "VerticalStickiness", "TopHorizontalStickiness", "BottomHorizontalStickiness", });
    internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(10);
    internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_descriptor,
        new java.lang.String[] { "SourceApp", "SourceJs", "Data", "Source", });
    internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceApp_descriptor =
      internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceApp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceApp_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceJs_descriptor =
      internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_descriptor.getNestedTypes().get(1);
    internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceJs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_BuyerGeneratedRequestData_SourceJs_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_BidRequest_AdSlot_MultiAdsCellInfo_descriptor =
      internal_static_BidRequest_AdSlot_descriptor.getNestedTypes().get(11);
    internal_static_BidRequest_AdSlot_MultiAdsCellInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_AdSlot_MultiAdsCellInfo_descriptor,
        new java.lang.String[] { "CellRow", "CellColumn", "GridRows", "GridColumns", "GridId", });
    internal_static_BidRequest_BidResponseFeedback_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(12);
    internal_static_BidRequest_BidResponseFeedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_BidResponseFeedback_descriptor,
        new java.lang.String[] { "RequestId", "CreativeIndex", "CreativeStatusCode", "CpmMicros", "MinimumBidToWin", "SampledMediationCpmAheadOfAuctionWinner", "EventNotificationToken", "BuyerCreativeId", });
    internal_static_BidRequest_SupplyChain_descriptor =
      internal_static_BidRequest_descriptor.getNestedTypes().get(13);
    internal_static_BidRequest_SupplyChain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_SupplyChain_descriptor,
        new java.lang.String[] { "Complete", "Nodes", "Version", });
    internal_static_BidRequest_SupplyChain_SupplyChainNode_descriptor =
      internal_static_BidRequest_SupplyChain_descriptor.getNestedTypes().get(0);
    internal_static_BidRequest_SupplyChain_SupplyChainNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_SupplyChain_SupplyChainNode_descriptor,
        new java.lang.String[] { "AdvertisingSystemIdentifier", "SellerIdentifier", "HandlesPayment", });
    internal_static_BidResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_descriptor,
        new java.lang.String[] { "Ad", "DebugString", "ProcessingTimeMs", "NoBidReason", });
    internal_static_BidResponse_Ad_descriptor =
      internal_static_BidResponse_descriptor.getNestedTypes().get(0);
    internal_static_BidResponse_Ad_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_descriptor,
        new java.lang.String[] { "EventNotificationToken", "BuyerCreativeId", "HtmlSnippet", "VideoUrl", "VideoVastXml", "AmpAdUrl", "NativeAd", "ClickThroughUrl", "VendorType", "Attribute", "Category", "RestrictedCategory", "AdvertiserName", "DEPRECATEDBidderName", "Width", "Height", "AgencyId", "Adslot", "ImpressionTrackingUrl", "ClickTrackingUrls", "AdChoicesDestinationUrl", "ImpressionTrackingResource", "SdkRenderedAd", "Skadn", });
    internal_static_BidResponse_Ad_NativeAd_descriptor =
      internal_static_BidResponse_Ad_descriptor.getNestedTypes().get(0);
    internal_static_BidResponse_Ad_NativeAd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_NativeAd_descriptor,
        new java.lang.String[] { "Headline", "Body", "CallToAction", "Advertiser", "Image", "Logo", "AppIcon", "VideoUrl", "VideoVastXml", "StarRating", "ClickLinkUrl", "DEPRECATEDClickTrackingUrl", "DEPRECATEDClickTrackingUrls", "Price", "Video", });
    internal_static_BidResponse_Ad_NativeAd_Image_descriptor =
      internal_static_BidResponse_Ad_NativeAd_descriptor.getNestedTypes().get(0);
    internal_static_BidResponse_Ad_NativeAd_Image_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_NativeAd_Image_descriptor,
        new java.lang.String[] { "Url", "Width", "Height", });
    internal_static_BidResponse_Ad_AdSlot_descriptor =
      internal_static_BidResponse_Ad_descriptor.getNestedTypes().get(1);
    internal_static_BidResponse_Ad_AdSlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_AdSlot_descriptor,
        new java.lang.String[] { "Id", "MaxCpmMicros", "MinCpmMicros", "BillingId", "DealId", "ExchangeDealId", "ExchangeDealType", "BuyerReportingId", "ThirdPartyBuyerToken", "FrequencyCap", });
    internal_static_BidResponse_Ad_AdSlot_FrequencyCap_descriptor =
      internal_static_BidResponse_Ad_AdSlot_descriptor.getNestedTypes().get(0);
    internal_static_BidResponse_Ad_AdSlot_FrequencyCap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_AdSlot_FrequencyCap_descriptor,
        new java.lang.String[] { "FrequencyCapId", "TimeUnit", "TimeRange", "MaxImpressions", });
    internal_static_BidResponse_Ad_ImpressionTrackingResource_descriptor =
      internal_static_BidResponse_Ad_descriptor.getNestedTypes().get(2);
    internal_static_BidResponse_Ad_ImpressionTrackingResource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_ImpressionTrackingResource_descriptor,
        new java.lang.String[] { "ScriptUrl", "Context", "VerificationParameters", "VendorKey", });
    internal_static_BidResponse_Ad_SdkRenderedAd_descriptor =
      internal_static_BidResponse_Ad_descriptor.getNestedTypes().get(3);
    internal_static_BidResponse_Ad_SdkRenderedAd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_SdkRenderedAd_descriptor,
        new java.lang.String[] { "Id", "RenderingData", "DeclaredAd", });
    internal_static_BidResponse_Ad_SdkRenderedAd_DeclaredAd_descriptor =
      internal_static_BidResponse_Ad_SdkRenderedAd_descriptor.getNestedTypes().get(0);
    internal_static_BidResponse_Ad_SdkRenderedAd_DeclaredAd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_SdkRenderedAd_DeclaredAd_descriptor,
        new java.lang.String[] { "HtmlSnippet", "VideoUrl", "VideoVastXml", "ClickThroughUrl", "Content", });
    internal_static_BidResponse_Ad_SKAdNetworkResponse_descriptor =
      internal_static_BidResponse_Ad_descriptor.getNestedTypes().get(4);
    internal_static_BidResponse_Ad_SKAdNetworkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_SKAdNetworkResponse_descriptor,
        new java.lang.String[] { "Version", "Network", "Campaign", "Itunesitem", "Fidelities", "Nonce", "Sourceapp", "Timestamp", "Signature", "SkadnOptions", });
    internal_static_BidResponse_Ad_SKAdNetworkResponse_Fidelity_descriptor =
      internal_static_BidResponse_Ad_SKAdNetworkResponse_descriptor.getNestedTypes().get(0);
    internal_static_BidResponse_Ad_SKAdNetworkResponse_Fidelity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_SKAdNetworkResponse_Fidelity_descriptor,
        new java.lang.String[] { "FidelityType", "Nonce", "Timestamp", "Signature", });
    internal_static_BidResponse_Ad_SKAdNetworkResponse_SKAdNetworkOptions_descriptor =
      internal_static_BidResponse_Ad_SKAdNetworkResponse_descriptor.getNestedTypes().get(1);
    internal_static_BidResponse_Ad_SKAdNetworkResponse_SKAdNetworkOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidResponse_Ad_SKAdNetworkResponse_SKAdNetworkOptions_descriptor,
        new java.lang.String[] { "AlwaysOpenAppstore", });
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
