// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtime-bidding.proto

package com.example.protobuf.google;

/**
 * <pre>
 * SKAdNetwork API starting from version 2.2 supports multiple ad
 * presentation options specified by the `fidelity-type` parameter of the
 * SKAdNetwork signature.  The following are the fidelity types supported by
 * Apple. For more info visit:
 * https://developer.apple.com/documentation/storekit/skadnetwork/signing_and_providing_ads
 * </pre>
 *
 * Protobuf enum {@code SKAdNetworkFidelityType}
 */
public enum SKAdNetworkFidelityType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Attribution for app installs within 24 hours of viewing an ad for at least
   * 3 seconds. Supported for SKAdnetwork version 2.2 and up. For more info see:
   * https://developer.apple.com/documentation/storekit/skadnetwork/generating_the_signature_to_validate_view-through_ads
   * </pre>
   *
   * <code>VIEW_THROUGH_ADS = 0;</code>
   */
  VIEW_THROUGH_ADS(0),
  /**
   * <pre>
   * Attribution for app installs initiated from the StoreKit-rendered App Store
   * product page driven by ad clicks. Supported for all SKAdNetwork versions.
   * For more info see:
   * https://developer.apple.com/documentation/storekit/skadnetwork/generating_the_signature_to_validate_storekit-rendered_ads
   * </pre>
   *
   * <code>STOREKIT_RENDERED_ADS = 1;</code>
   */
  STOREKIT_RENDERED_ADS(1),
  ;

  /**
   * <pre>
   * Attribution for app installs within 24 hours of viewing an ad for at least
   * 3 seconds. Supported for SKAdnetwork version 2.2 and up. For more info see:
   * https://developer.apple.com/documentation/storekit/skadnetwork/generating_the_signature_to_validate_view-through_ads
   * </pre>
   *
   * <code>VIEW_THROUGH_ADS = 0;</code>
   */
  public static final int VIEW_THROUGH_ADS_VALUE = 0;
  /**
   * <pre>
   * Attribution for app installs initiated from the StoreKit-rendered App Store
   * product page driven by ad clicks. Supported for all SKAdNetwork versions.
   * For more info see:
   * https://developer.apple.com/documentation/storekit/skadnetwork/generating_the_signature_to_validate_storekit-rendered_ads
   * </pre>
   *
   * <code>STOREKIT_RENDERED_ADS = 1;</code>
   */
  public static final int STOREKIT_RENDERED_ADS_VALUE = 1;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SKAdNetworkFidelityType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SKAdNetworkFidelityType forNumber(int value) {
    switch (value) {
      case 0: return VIEW_THROUGH_ADS;
      case 1: return STOREKIT_RENDERED_ADS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SKAdNetworkFidelityType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SKAdNetworkFidelityType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SKAdNetworkFidelityType>() {
          public SKAdNetworkFidelityType findValueByNumber(int number) {
            return SKAdNetworkFidelityType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.protobuf.google.RealtimeBidding.getDescriptor().getEnumTypes().get(0);
  }

  private static final SKAdNetworkFidelityType[] VALUES = values();

  public static SKAdNetworkFidelityType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SKAdNetworkFidelityType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:SKAdNetworkFidelityType)
}

